// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComicUpdateListResponse.proto

package com.example.dmzj_api.proto;

public final class ComicUpdateList {
  private ComicUpdateList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComicUpdateListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.proto.ComicUpdateListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    int getErrno();

    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    java.lang.String getErrmsg();
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> 
        getDataList();
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getData(int index);
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    java.util.List<? extends com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.proto.ComicUpdateListResponse}
   */
  public static final class ComicUpdateListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.proto.ComicUpdateListResponse)
      ComicUpdateListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComicUpdateListResponse.newBuilder() to construct.
    private ComicUpdateListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComicUpdateListResponse() {
      errmsg_ = "";
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComicUpdateListResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.class, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.Builder.class);
    }

    public static final int ERRNO_FIELD_NUMBER = 1;
    private int errno_ = 0;
    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    @java.lang.Override
    public int getErrno() {
      return errno_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errmsg_ = "";
    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    @java.lang.Override
    public java.lang.String getErrmsg() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errmsg_ = s;
        return s;
      }
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> data_;
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errno_ != 0) {
        output.writeInt32(1, errno_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errmsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errmsg_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(3, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errno_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errno_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errmsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errmsg_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse)) {
        return super.equals(obj);
      }
      com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse other = (com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse) obj;

      if (getErrno()
          != other.getErrno()) return false;
      if (!getErrmsg()
          .equals(other.getErrmsg())) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRNO_FIELD_NUMBER;
      hash = (53 * hash) + getErrno();
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrmsg().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.dmzj_api.proto.ComicUpdateListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.proto.ComicUpdateListResponse)
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.class, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.Builder.class);
      }

      // Construct using com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        errno_ = 0;
        errmsg_ = "";
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
        } else {
          data_ = null;
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor;
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse getDefaultInstanceForType() {
        return com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse build() {
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse buildPartial() {
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse result = new com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse result) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
      }

      private void buildPartial0(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errno_ = errno_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.errmsg_ = errmsg_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse) {
          return mergeFrom((com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse other) {
        if (other == com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse.getDefaultInstance()) return this;
        if (other.getErrno() != 0) {
          setErrno(other.getErrno());
        }
        if (!other.getErrmsg().isEmpty()) {
          errmsg_ = other.errmsg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000004);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errno_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                errmsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse m =
                    input.readMessage(
                        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.parser(),
                        extensionRegistry);
                if (dataBuilder_ == null) {
                  ensureDataIsMutable();
                  data_.add(m);
                } else {
                  dataBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int errno_ ;
      /**
       * <code>int32 Errno = 1;</code>
       * @return The errno.
       */
      @java.lang.Override
      public int getErrno() {
        return errno_;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @param value The errno to set.
       * @return This builder for chaining.
       */
      public Builder setErrno(int value) {

        errno_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrno() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errno_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errmsg_ = "";
      /**
       * <code>string Errmsg = 2;</code>
       * @return The errmsg.
       */
      public java.lang.String getErrmsg() {
        java.lang.Object ref = errmsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errmsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return The bytes for errmsg.
       */
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        java.lang.Object ref = errmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errmsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrmsg() {
        errmsg_ = getDefaultInstance().getErrmsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The bytes for errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        errmsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          data_ = new java.util.ArrayList<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse>(data_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder> dataBuilder_;

      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder addData(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder addData(
          com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public java.util.List<? extends com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.dmzj_api.proto.ComicUpdateListItemResponse Data = 3;</code>
       */
      public java.util.List<com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.proto.ComicUpdateListResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.proto.ComicUpdateListResponse)
    private static final com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse();
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComicUpdateListResponse>
        PARSER = new com.google.protobuf.AbstractParser<ComicUpdateListResponse>() {
      @java.lang.Override
      public ComicUpdateListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComicUpdateListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComicUpdateListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComicUpdateListItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.proto.ComicUpdateListItemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ComicId = 1;</code>
     * @return The comicId.
     */
    int getComicId();

    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>bool Islong = 3;</code>
     * @return The islong.
     */
    boolean getIslong();

    /**
     * <code>string Authors = 4;</code>
     * @return The authors.
     */
    java.lang.String getAuthors();
    /**
     * <code>string Authors = 4;</code>
     * @return The bytes for authors.
     */
    com.google.protobuf.ByteString
        getAuthorsBytes();

    /**
     * <code>string Types = 5;</code>
     * @return The types.
     */
    java.lang.String getTypes();
    /**
     * <code>string Types = 5;</code>
     * @return The bytes for types.
     */
    com.google.protobuf.ByteString
        getTypesBytes();

    /**
     * <code>string Cover = 6;</code>
     * @return The cover.
     */
    java.lang.String getCover();
    /**
     * <code>string Cover = 6;</code>
     * @return The bytes for cover.
     */
    com.google.protobuf.ByteString
        getCoverBytes();

    /**
     * <code>string Status = 7;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string Status = 7;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The lastUpdateChapterName.
     */
    java.lang.String getLastUpdateChapterName();
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes();

    /**
     * <code>int32 LastUpdateChapterId = 9;</code>
     * @return The lastUpdateChapterId.
     */
    int getLastUpdateChapterId();

    /**
     * <code>int64 LastUpdatetime = 10;</code>
     * @return The lastUpdatetime.
     */
    long getLastUpdatetime();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.proto.ComicUpdateListItemResponse}
   */
  public static final class ComicUpdateListItemResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.proto.ComicUpdateListItemResponse)
      ComicUpdateListItemResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComicUpdateListItemResponse.newBuilder() to construct.
    private ComicUpdateListItemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComicUpdateListItemResponse() {
      title_ = "";
      authors_ = "";
      types_ = "";
      cover_ = "";
      status_ = "";
      lastUpdateChapterName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComicUpdateListItemResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.class, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder.class);
    }

    public static final int COMICID_FIELD_NUMBER = 1;
    private int comicId_ = 0;
    /**
     * <code>int32 ComicId = 1;</code>
     * @return The comicId.
     */
    @java.lang.Override
    public int getComicId() {
      return comicId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISLONG_FIELD_NUMBER = 3;
    private boolean islong_ = false;
    /**
     * <code>bool Islong = 3;</code>
     * @return The islong.
     */
    @java.lang.Override
    public boolean getIslong() {
      return islong_;
    }

    public static final int AUTHORS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object authors_ = "";
    /**
     * <code>string Authors = 4;</code>
     * @return The authors.
     */
    @java.lang.Override
    public java.lang.String getAuthors() {
      java.lang.Object ref = authors_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authors_ = s;
        return s;
      }
    }
    /**
     * <code>string Authors = 4;</code>
     * @return The bytes for authors.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorsBytes() {
      java.lang.Object ref = authors_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPES_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object types_ = "";
    /**
     * <code>string Types = 5;</code>
     * @return The types.
     */
    @java.lang.Override
    public java.lang.String getTypes() {
      java.lang.Object ref = types_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        types_ = s;
        return s;
      }
    }
    /**
     * <code>string Types = 5;</code>
     * @return The bytes for types.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypesBytes() {
      java.lang.Object ref = types_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        types_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVER_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cover_ = "";
    /**
     * <code>string Cover = 6;</code>
     * @return The cover.
     */
    @java.lang.Override
    public java.lang.String getCover() {
      java.lang.Object ref = cover_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cover_ = s;
        return s;
      }
    }
    /**
     * <code>string Cover = 6;</code>
     * @return The bytes for cover.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoverBytes() {
      java.lang.Object ref = cover_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cover_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string Status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string Status = 7;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTUPDATECHAPTERNAME_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastUpdateChapterName_ = "";
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The lastUpdateChapterName.
     */
    @java.lang.Override
    public java.lang.String getLastUpdateChapterName() {
      java.lang.Object ref = lastUpdateChapterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUpdateChapterName_ = s;
        return s;
      }
    }
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes() {
      java.lang.Object ref = lastUpdateChapterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUpdateChapterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTUPDATECHAPTERID_FIELD_NUMBER = 9;
    private int lastUpdateChapterId_ = 0;
    /**
     * <code>int32 LastUpdateChapterId = 9;</code>
     * @return The lastUpdateChapterId.
     */
    @java.lang.Override
    public int getLastUpdateChapterId() {
      return lastUpdateChapterId_;
    }

    public static final int LASTUPDATETIME_FIELD_NUMBER = 10;
    private long lastUpdatetime_ = 0L;
    /**
     * <code>int64 LastUpdatetime = 10;</code>
     * @return The lastUpdatetime.
     */
    @java.lang.Override
    public long getLastUpdatetime() {
      return lastUpdatetime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (comicId_ != 0) {
        output.writeInt32(1, comicId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (islong_ != false) {
        output.writeBool(3, islong_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authors_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authors_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(types_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, types_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cover_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastUpdateChapterName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lastUpdateChapterName_);
      }
      if (lastUpdateChapterId_ != 0) {
        output.writeInt32(9, lastUpdateChapterId_);
      }
      if (lastUpdatetime_ != 0L) {
        output.writeInt64(10, lastUpdatetime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (comicId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, comicId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (islong_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, islong_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authors_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authors_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(types_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, types_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cover_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastUpdateChapterName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lastUpdateChapterName_);
      }
      if (lastUpdateChapterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, lastUpdateChapterId_);
      }
      if (lastUpdatetime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, lastUpdatetime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse)) {
        return super.equals(obj);
      }
      com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse other = (com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse) obj;

      if (getComicId()
          != other.getComicId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (getIslong()
          != other.getIslong()) return false;
      if (!getAuthors()
          .equals(other.getAuthors())) return false;
      if (!getTypes()
          .equals(other.getTypes())) return false;
      if (!getCover()
          .equals(other.getCover())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getLastUpdateChapterName()
          .equals(other.getLastUpdateChapterName())) return false;
      if (getLastUpdateChapterId()
          != other.getLastUpdateChapterId()) return false;
      if (getLastUpdatetime()
          != other.getLastUpdatetime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMICID_FIELD_NUMBER;
      hash = (53 * hash) + getComicId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + ISLONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIslong());
      hash = (37 * hash) + AUTHORS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthors().hashCode();
      hash = (37 * hash) + TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTypes().hashCode();
      hash = (37 * hash) + COVER_FIELD_NUMBER;
      hash = (53 * hash) + getCover().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + LASTUPDATECHAPTERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdateChapterName().hashCode();
      hash = (37 * hash) + LASTUPDATECHAPTERID_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdateChapterId();
      hash = (37 * hash) + LASTUPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastUpdatetime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.dmzj_api.proto.ComicUpdateListItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.proto.ComicUpdateListItemResponse)
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.class, com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.Builder.class);
      }

      // Construct using com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        comicId_ = 0;
        title_ = "";
        islong_ = false;
        authors_ = "";
        types_ = "";
        cover_ = "";
        status_ = "";
        lastUpdateChapterName_ = "";
        lastUpdateChapterId_ = 0;
        lastUpdatetime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.dmzj_api.proto.ComicUpdateList.internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor;
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getDefaultInstanceForType() {
        return com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse build() {
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse buildPartial() {
        com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse result = new com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.comicId_ = comicId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.islong_ = islong_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.authors_ = authors_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.types_ = types_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.cover_ = cover_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.lastUpdateChapterName_ = lastUpdateChapterName_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.lastUpdateChapterId_ = lastUpdateChapterId_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.lastUpdatetime_ = lastUpdatetime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse) {
          return mergeFrom((com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse other) {
        if (other == com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse.getDefaultInstance()) return this;
        if (other.getComicId() != 0) {
          setComicId(other.getComicId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getIslong() != false) {
          setIslong(other.getIslong());
        }
        if (!other.getAuthors().isEmpty()) {
          authors_ = other.authors_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getTypes().isEmpty()) {
          types_ = other.types_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getCover().isEmpty()) {
          cover_ = other.cover_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getLastUpdateChapterName().isEmpty()) {
          lastUpdateChapterName_ = other.lastUpdateChapterName_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.getLastUpdateChapterId() != 0) {
          setLastUpdateChapterId(other.getLastUpdateChapterId());
        }
        if (other.getLastUpdatetime() != 0L) {
          setLastUpdatetime(other.getLastUpdatetime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                comicId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                islong_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                authors_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                types_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                cover_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                lastUpdateChapterName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 72: {
                lastUpdateChapterId_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                lastUpdatetime_ = input.readInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int comicId_ ;
      /**
       * <code>int32 ComicId = 1;</code>
       * @return The comicId.
       */
      @java.lang.Override
      public int getComicId() {
        return comicId_;
      }
      /**
       * <code>int32 ComicId = 1;</code>
       * @param value The comicId to set.
       * @return This builder for chaining.
       */
      public Builder setComicId(int value) {

        comicId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ComicId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearComicId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        comicId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean islong_ ;
      /**
       * <code>bool Islong = 3;</code>
       * @return The islong.
       */
      @java.lang.Override
      public boolean getIslong() {
        return islong_;
      }
      /**
       * <code>bool Islong = 3;</code>
       * @param value The islong to set.
       * @return This builder for chaining.
       */
      public Builder setIslong(boolean value) {

        islong_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool Islong = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIslong() {
        bitField0_ = (bitField0_ & ~0x00000004);
        islong_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object authors_ = "";
      /**
       * <code>string Authors = 4;</code>
       * @return The authors.
       */
      public java.lang.String getAuthors() {
        java.lang.Object ref = authors_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authors_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Authors = 4;</code>
       * @return The bytes for authors.
       */
      public com.google.protobuf.ByteString
          getAuthorsBytes() {
        java.lang.Object ref = authors_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authors_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Authors = 4;</code>
       * @param value The authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthors(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        authors_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string Authors = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthors() {
        authors_ = getDefaultInstance().getAuthors();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string Authors = 4;</code>
       * @param value The bytes for authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        authors_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object types_ = "";
      /**
       * <code>string Types = 5;</code>
       * @return The types.
       */
      public java.lang.String getTypes() {
        java.lang.Object ref = types_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          types_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Types = 5;</code>
       * @return The bytes for types.
       */
      public com.google.protobuf.ByteString
          getTypesBytes() {
        java.lang.Object ref = types_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          types_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Types = 5;</code>
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        types_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string Types = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        types_ = getDefaultInstance().getTypes();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string Types = 5;</code>
       * @param value The bytes for types to set.
       * @return This builder for chaining.
       */
      public Builder setTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        types_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object cover_ = "";
      /**
       * <code>string Cover = 6;</code>
       * @return The cover.
       */
      public java.lang.String getCover() {
        java.lang.Object ref = cover_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cover_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Cover = 6;</code>
       * @return The bytes for cover.
       */
      public com.google.protobuf.ByteString
          getCoverBytes() {
        java.lang.Object ref = cover_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cover_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Cover = 6;</code>
       * @param value The cover to set.
       * @return This builder for chaining.
       */
      public Builder setCover(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cover_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string Cover = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCover() {
        cover_ = getDefaultInstance().getCover();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string Cover = 6;</code>
       * @param value The bytes for cover to set.
       * @return This builder for chaining.
       */
      public Builder setCoverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cover_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string Status = 7;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Status = 7;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Status = 7;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string Status = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string Status = 7;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object lastUpdateChapterName_ = "";
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return The lastUpdateChapterName.
       */
      public java.lang.String getLastUpdateChapterName() {
        java.lang.Object ref = lastUpdateChapterName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastUpdateChapterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return The bytes for lastUpdateChapterName.
       */
      public com.google.protobuf.ByteString
          getLastUpdateChapterNameBytes() {
        java.lang.Object ref = lastUpdateChapterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastUpdateChapterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @param value The lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastUpdateChapterName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateChapterName() {
        lastUpdateChapterName_ = getDefaultInstance().getLastUpdateChapterName();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @param value The bytes for lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastUpdateChapterName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private int lastUpdateChapterId_ ;
      /**
       * <code>int32 LastUpdateChapterId = 9;</code>
       * @return The lastUpdateChapterId.
       */
      @java.lang.Override
      public int getLastUpdateChapterId() {
        return lastUpdateChapterId_;
      }
      /**
       * <code>int32 LastUpdateChapterId = 9;</code>
       * @param value The lastUpdateChapterId to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterId(int value) {

        lastUpdateChapterId_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 LastUpdateChapterId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateChapterId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastUpdateChapterId_ = 0;
        onChanged();
        return this;
      }

      private long lastUpdatetime_ ;
      /**
       * <code>int64 LastUpdatetime = 10;</code>
       * @return The lastUpdatetime.
       */
      @java.lang.Override
      public long getLastUpdatetime() {
        return lastUpdatetime_;
      }
      /**
       * <code>int64 LastUpdatetime = 10;</code>
       * @param value The lastUpdatetime to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdatetime(long value) {

        lastUpdatetime_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>int64 LastUpdatetime = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdatetime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lastUpdatetime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.proto.ComicUpdateListItemResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.proto.ComicUpdateListItemResponse)
    private static final com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse();
    }

    public static com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComicUpdateListItemResponse>
        PARSER = new com.google.protobuf.AbstractParser<ComicUpdateListItemResponse>() {
      @java.lang.Override
      public ComicUpdateListItemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComicUpdateListItemResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComicUpdateListItemResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.dmzj_api.proto.ComicUpdateList.ComicUpdateListItemResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ComicUpdateListResponse.proto\022\032com.exa" +
      "mple.dmzj_api.proto\"\177\n\027ComicUpdateListRe" +
      "sponse\022\r\n\005Errno\030\001 \001(\005\022\016\n\006Errmsg\030\002 \001(\t\022E\n" +
      "\004Data\030\003 \003(\01327.com.example.dmzj_api.proto" +
      ".ComicUpdateListItemResponse\"\340\001\n\033ComicUp" +
      "dateListItemResponse\022\017\n\007ComicId\030\001 \001(\005\022\r\n" +
      "\005Title\030\002 \001(\t\022\016\n\006Islong\030\003 \001(\010\022\017\n\007Authors\030" +
      "\004 \001(\t\022\r\n\005Types\030\005 \001(\t\022\r\n\005Cover\030\006 \001(\t\022\016\n\006S" +
      "tatus\030\007 \001(\t\022\035\n\025LastUpdateChapterName\030\010 \001" +
      "(\t\022\033\n\023LastUpdateChapterId\030\t \001(\005\022\026\n\016LastU" +
      "pdatetime\030\n \001(\003B\021B\017ComicUpdateListb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_dmzj_api_proto_ComicUpdateListResponse_descriptor,
        new java.lang.String[] { "Errno", "Errmsg", "Data", });
    internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_dmzj_api_proto_ComicUpdateListItemResponse_descriptor,
        new java.lang.String[] { "ComicId", "Title", "Islong", "Authors", "Types", "Cover", "Status", "LastUpdateChapterName", "LastUpdateChapterId", "LastUpdatetime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
