// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComicRankListResponse.proto

package com.example.dmzj_api.pojo;

public final class ComicRankListRes {
  private ComicRankListRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ComicRankListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.ComicRankListResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    int getErrno();

    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    java.lang.String getErrmsg();
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    java.util.List<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> 
        getDataList();
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse getData(int index);
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.ComicRankListResponse}
   */
  public  static final class ComicRankListResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ComicRankListResponse, ComicRankListResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.ComicRankListResponse)
      ComicRankListResponseOrBuilder {
    private ComicRankListResponse() {
      errmsg_ = "";
      data_ = emptyProtobufList();
    }
    public static final int ERRNO_FIELD_NUMBER = 1;
    private int errno_;
    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    @java.lang.Override
    public int getErrno() {
      return errno_;
    }
    /**
     * <code>int32 Errno = 1;</code>
     * @param value The errno to set.
     */
    private void setErrno(int value) {
      
      errno_ = value;
    }
    /**
     * <code>int32 Errno = 1;</code>
     */
    private void clearErrno() {
      
      errno_ = 0;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.String errmsg_;
    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    @java.lang.Override
    public java.lang.String getErrmsg() {
      return errmsg_;
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errmsg_);
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The errmsg to set.
     */
    private void setErrmsg(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      errmsg_ = value;
    }
    /**
     * <code>string Errmsg = 2;</code>
     */
    private void clearErrmsg() {
      
      errmsg_ = getDefaultInstance().getErrmsg();
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The bytes for errmsg to set.
     */
    private void setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errmsg_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> data_;
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    public java.util.List<? extends com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponseOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    public com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponseOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> tmp = data_;
      if (!tmp.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void setData(
        int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void addData(com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void addData(
        int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void addAllData(
        java.lang.Iterable<? extends com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.ComicRankListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.ComicRankListResponse)
        com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 Errno = 1;</code>
       * @return The errno.
       */
      @java.lang.Override
      public int getErrno() {
        return instance.getErrno();
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @param value The errno to set.
       * @return This builder for chaining.
       */
      public Builder setErrno(int value) {
        copyOnWrite();
        instance.setErrno(value);
        return this;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrno() {
        copyOnWrite();
        instance.clearErrno();
        return this;
      }

      /**
       * <code>string Errmsg = 2;</code>
       * @return The errmsg.
       */
      @java.lang.Override
      public java.lang.String getErrmsg() {
        return instance.getErrmsg();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return The bytes for errmsg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        return instance.getErrmsgBytes();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrmsg(value);
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrmsg() {
        copyOnWrite();
        instance.clearErrmsg();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The bytes for errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrmsgBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse getData(int index) {
        return instance.getData(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder addData(com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder addData(
          com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.ComicRankListItemResponse Data = 3;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.ComicRankListResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "errno_",
              "errmsg_",
              "data_",
              com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.ComicRankListResponse)
    private static final com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse DEFAULT_INSTANCE;
    static {
      ComicRankListResponse defaultInstance = new ComicRankListResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ComicRankListResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ComicRankListResponse> PARSER;

    public static com.google.protobuf.Parser<ComicRankListResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ComicRankListItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.ComicRankListItemResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 ComicId = 1;</code>
     * @return The comicId.
     */
    int getComicId();

    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string Authors = 3;</code>
     * @return The authors.
     */
    java.lang.String getAuthors();
    /**
     * <code>string Authors = 3;</code>
     * @return The bytes for authors.
     */
    com.google.protobuf.ByteString
        getAuthorsBytes();

    /**
     * <code>string Status = 4;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string Status = 4;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string Cover = 5;</code>
     * @return The cover.
     */
    java.lang.String getCover();
    /**
     * <code>string Cover = 5;</code>
     * @return The bytes for cover.
     */
    com.google.protobuf.ByteString
        getCoverBytes();

    /**
     * <code>string Types = 6;</code>
     * @return The types.
     */
    java.lang.String getTypes();
    /**
     * <code>string Types = 6;</code>
     * @return The bytes for types.
     */
    com.google.protobuf.ByteString
        getTypesBytes();

    /**
     * <code>int64 LastUpdatetime = 7;</code>
     * @return The lastUpdatetime.
     */
    long getLastUpdatetime();

    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The lastUpdateChapterName.
     */
    java.lang.String getLastUpdateChapterName();
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes();

    /**
     * <code>string ComicPy = 9;</code>
     * @return The comicPy.
     */
    java.lang.String getComicPy();
    /**
     * <code>string ComicPy = 9;</code>
     * @return The bytes for comicPy.
     */
    com.google.protobuf.ByteString
        getComicPyBytes();

    /**
     * <code>int32 Num = 10;</code>
     * @return The num.
     */
    int getNum();

    /**
     * <code>int32 TagId = 11;</code>
     * @return The tagId.
     */
    int getTagId();

    /**
     * <code>string ChapterName = 12;</code>
     * @return The chapterName.
     */
    java.lang.String getChapterName();
    /**
     * <code>string ChapterName = 12;</code>
     * @return The bytes for chapterName.
     */
    com.google.protobuf.ByteString
        getChapterNameBytes();

    /**
     * <code>int32 ChapterId = 13;</code>
     * @return The chapterId.
     */
    int getChapterId();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.ComicRankListItemResponse}
   */
  public  static final class ComicRankListItemResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ComicRankListItemResponse, ComicRankListItemResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.ComicRankListItemResponse)
      ComicRankListItemResponseOrBuilder {
    private ComicRankListItemResponse() {
      title_ = "";
      authors_ = "";
      status_ = "";
      cover_ = "";
      types_ = "";
      lastUpdateChapterName_ = "";
      comicPy_ = "";
      chapterName_ = "";
    }
    public static final int COMICID_FIELD_NUMBER = 1;
    private int comicId_;
    /**
     * <code>int32 ComicId = 1;</code>
     * @return The comicId.
     */
    @java.lang.Override
    public int getComicId() {
      return comicId_;
    }
    /**
     * <code>int32 ComicId = 1;</code>
     * @param value The comicId to set.
     */
    private void setComicId(int value) {
      
      comicId_ = value;
    }
    /**
     * <code>int32 ComicId = 1;</code>
     */
    private void clearComicId() {
      
      comicId_ = 0;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.String title_;
    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>string Title = 2;</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      title_ = value;
    }
    /**
     * <code>string Title = 2;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>string Title = 2;</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();
      
    }

    public static final int AUTHORS_FIELD_NUMBER = 3;
    private java.lang.String authors_;
    /**
     * <code>string Authors = 3;</code>
     * @return The authors.
     */
    @java.lang.Override
    public java.lang.String getAuthors() {
      return authors_;
    }
    /**
     * <code>string Authors = 3;</code>
     * @return The bytes for authors.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(authors_);
    }
    /**
     * <code>string Authors = 3;</code>
     * @param value The authors to set.
     */
    private void setAuthors(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      authors_ = value;
    }
    /**
     * <code>string Authors = 3;</code>
     */
    private void clearAuthors() {
      
      authors_ = getDefaultInstance().getAuthors();
    }
    /**
     * <code>string Authors = 3;</code>
     * @param value The bytes for authors to set.
     */
    private void setAuthorsBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      authors_ = value.toStringUtf8();
      
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private java.lang.String status_;
    /**
     * <code>string Status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      return status_;
    }
    /**
     * <code>string Status = 4;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(status_);
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The status to set.
     */
    private void setStatus(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      status_ = value;
    }
    /**
     * <code>string Status = 4;</code>
     */
    private void clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The bytes for status to set.
     */
    private void setStatusBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      status_ = value.toStringUtf8();
      
    }

    public static final int COVER_FIELD_NUMBER = 5;
    private java.lang.String cover_;
    /**
     * <code>string Cover = 5;</code>
     * @return The cover.
     */
    @java.lang.Override
    public java.lang.String getCover() {
      return cover_;
    }
    /**
     * <code>string Cover = 5;</code>
     * @return The bytes for cover.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoverBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cover_);
    }
    /**
     * <code>string Cover = 5;</code>
     * @param value The cover to set.
     */
    private void setCover(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      cover_ = value;
    }
    /**
     * <code>string Cover = 5;</code>
     */
    private void clearCover() {
      
      cover_ = getDefaultInstance().getCover();
    }
    /**
     * <code>string Cover = 5;</code>
     * @param value The bytes for cover to set.
     */
    private void setCoverBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cover_ = value.toStringUtf8();
      
    }

    public static final int TYPES_FIELD_NUMBER = 6;
    private java.lang.String types_;
    /**
     * <code>string Types = 6;</code>
     * @return The types.
     */
    @java.lang.Override
    public java.lang.String getTypes() {
      return types_;
    }
    /**
     * <code>string Types = 6;</code>
     * @return The bytes for types.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypesBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(types_);
    }
    /**
     * <code>string Types = 6;</code>
     * @param value The types to set.
     */
    private void setTypes(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      types_ = value;
    }
    /**
     * <code>string Types = 6;</code>
     */
    private void clearTypes() {
      
      types_ = getDefaultInstance().getTypes();
    }
    /**
     * <code>string Types = 6;</code>
     * @param value The bytes for types to set.
     */
    private void setTypesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      types_ = value.toStringUtf8();
      
    }

    public static final int LASTUPDATETIME_FIELD_NUMBER = 7;
    private long lastUpdatetime_;
    /**
     * <code>int64 LastUpdatetime = 7;</code>
     * @return The lastUpdatetime.
     */
    @java.lang.Override
    public long getLastUpdatetime() {
      return lastUpdatetime_;
    }
    /**
     * <code>int64 LastUpdatetime = 7;</code>
     * @param value The lastUpdatetime to set.
     */
    private void setLastUpdatetime(long value) {
      
      lastUpdatetime_ = value;
    }
    /**
     * <code>int64 LastUpdatetime = 7;</code>
     */
    private void clearLastUpdatetime() {
      
      lastUpdatetime_ = 0L;
    }

    public static final int LASTUPDATECHAPTERNAME_FIELD_NUMBER = 8;
    private java.lang.String lastUpdateChapterName_;
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The lastUpdateChapterName.
     */
    @java.lang.Override
    public java.lang.String getLastUpdateChapterName() {
      return lastUpdateChapterName_;
    }
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lastUpdateChapterName_);
    }
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @param value The lastUpdateChapterName to set.
     */
    private void setLastUpdateChapterName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      lastUpdateChapterName_ = value;
    }
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     */
    private void clearLastUpdateChapterName() {
      
      lastUpdateChapterName_ = getDefaultInstance().getLastUpdateChapterName();
    }
    /**
     * <code>string LastUpdateChapterName = 8;</code>
     * @param value The bytes for lastUpdateChapterName to set.
     */
    private void setLastUpdateChapterNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lastUpdateChapterName_ = value.toStringUtf8();
      
    }

    public static final int COMICPY_FIELD_NUMBER = 9;
    private java.lang.String comicPy_;
    /**
     * <code>string ComicPy = 9;</code>
     * @return The comicPy.
     */
    @java.lang.Override
    public java.lang.String getComicPy() {
      return comicPy_;
    }
    /**
     * <code>string ComicPy = 9;</code>
     * @return The bytes for comicPy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getComicPyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(comicPy_);
    }
    /**
     * <code>string ComicPy = 9;</code>
     * @param value The comicPy to set.
     */
    private void setComicPy(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      comicPy_ = value;
    }
    /**
     * <code>string ComicPy = 9;</code>
     */
    private void clearComicPy() {
      
      comicPy_ = getDefaultInstance().getComicPy();
    }
    /**
     * <code>string ComicPy = 9;</code>
     * @param value The bytes for comicPy to set.
     */
    private void setComicPyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      comicPy_ = value.toStringUtf8();
      
    }

    public static final int NUM_FIELD_NUMBER = 10;
    private int num_;
    /**
     * <code>int32 Num = 10;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }
    /**
     * <code>int32 Num = 10;</code>
     * @param value The num to set.
     */
    private void setNum(int value) {
      
      num_ = value;
    }
    /**
     * <code>int32 Num = 10;</code>
     */
    private void clearNum() {
      
      num_ = 0;
    }

    public static final int TAGID_FIELD_NUMBER = 11;
    private int tagId_;
    /**
     * <code>int32 TagId = 11;</code>
     * @return The tagId.
     */
    @java.lang.Override
    public int getTagId() {
      return tagId_;
    }
    /**
     * <code>int32 TagId = 11;</code>
     * @param value The tagId to set.
     */
    private void setTagId(int value) {
      
      tagId_ = value;
    }
    /**
     * <code>int32 TagId = 11;</code>
     */
    private void clearTagId() {
      
      tagId_ = 0;
    }

    public static final int CHAPTERNAME_FIELD_NUMBER = 12;
    private java.lang.String chapterName_;
    /**
     * <code>string ChapterName = 12;</code>
     * @return The chapterName.
     */
    @java.lang.Override
    public java.lang.String getChapterName() {
      return chapterName_;
    }
    /**
     * <code>string ChapterName = 12;</code>
     * @return The bytes for chapterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChapterNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(chapterName_);
    }
    /**
     * <code>string ChapterName = 12;</code>
     * @param value The chapterName to set.
     */
    private void setChapterName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      chapterName_ = value;
    }
    /**
     * <code>string ChapterName = 12;</code>
     */
    private void clearChapterName() {
      
      chapterName_ = getDefaultInstance().getChapterName();
    }
    /**
     * <code>string ChapterName = 12;</code>
     * @param value The bytes for chapterName to set.
     */
    private void setChapterNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      chapterName_ = value.toStringUtf8();
      
    }

    public static final int CHAPTERID_FIELD_NUMBER = 13;
    private int chapterId_;
    /**
     * <code>int32 ChapterId = 13;</code>
     * @return The chapterId.
     */
    @java.lang.Override
    public int getChapterId() {
      return chapterId_;
    }
    /**
     * <code>int32 ChapterId = 13;</code>
     * @param value The chapterId to set.
     */
    private void setChapterId(int value) {
      
      chapterId_ = value;
    }
    /**
     * <code>int32 ChapterId = 13;</code>
     */
    private void clearChapterId() {
      
      chapterId_ = 0;
    }

    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.ComicRankListItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.ComicRankListItemResponse)
        com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 ComicId = 1;</code>
       * @return The comicId.
       */
      @java.lang.Override
      public int getComicId() {
        return instance.getComicId();
      }
      /**
       * <code>int32 ComicId = 1;</code>
       * @param value The comicId to set.
       * @return This builder for chaining.
       */
      public Builder setComicId(int value) {
        copyOnWrite();
        instance.setComicId(value);
        return this;
      }
      /**
       * <code>int32 ComicId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearComicId() {
        copyOnWrite();
        instance.clearComicId();
        return this;
      }

      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>string Authors = 3;</code>
       * @return The authors.
       */
      @java.lang.Override
      public java.lang.String getAuthors() {
        return instance.getAuthors();
      }
      /**
       * <code>string Authors = 3;</code>
       * @return The bytes for authors.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAuthorsBytes() {
        return instance.getAuthorsBytes();
      }
      /**
       * <code>string Authors = 3;</code>
       * @param value The authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthors(
          java.lang.String value) {
        copyOnWrite();
        instance.setAuthors(value);
        return this;
      }
      /**
       * <code>string Authors = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthors() {
        copyOnWrite();
        instance.clearAuthors();
        return this;
      }
      /**
       * <code>string Authors = 3;</code>
       * @param value The bytes for authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAuthorsBytes(value);
        return this;
      }

      /**
       * <code>string Status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public java.lang.String getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>string Status = 4;</code>
       * @return The bytes for status.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStatusBytes() {
        return instance.getStatusBytes();
      }
      /**
       * <code>string Status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>string Status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }
      /**
       * <code>string Status = 4;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStatusBytes(value);
        return this;
      }

      /**
       * <code>string Cover = 5;</code>
       * @return The cover.
       */
      @java.lang.Override
      public java.lang.String getCover() {
        return instance.getCover();
      }
      /**
       * <code>string Cover = 5;</code>
       * @return The bytes for cover.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCoverBytes() {
        return instance.getCoverBytes();
      }
      /**
       * <code>string Cover = 5;</code>
       * @param value The cover to set.
       * @return This builder for chaining.
       */
      public Builder setCover(
          java.lang.String value) {
        copyOnWrite();
        instance.setCover(value);
        return this;
      }
      /**
       * <code>string Cover = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCover() {
        copyOnWrite();
        instance.clearCover();
        return this;
      }
      /**
       * <code>string Cover = 5;</code>
       * @param value The bytes for cover to set.
       * @return This builder for chaining.
       */
      public Builder setCoverBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCoverBytes(value);
        return this;
      }

      /**
       * <code>string Types = 6;</code>
       * @return The types.
       */
      @java.lang.Override
      public java.lang.String getTypes() {
        return instance.getTypes();
      }
      /**
       * <code>string Types = 6;</code>
       * @return The bytes for types.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypesBytes() {
        return instance.getTypesBytes();
      }
      /**
       * <code>string Types = 6;</code>
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          java.lang.String value) {
        copyOnWrite();
        instance.setTypes(value);
        return this;
      }
      /**
       * <code>string Types = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        copyOnWrite();
        instance.clearTypes();
        return this;
      }
      /**
       * <code>string Types = 6;</code>
       * @param value The bytes for types to set.
       * @return This builder for chaining.
       */
      public Builder setTypesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypesBytes(value);
        return this;
      }

      /**
       * <code>int64 LastUpdatetime = 7;</code>
       * @return The lastUpdatetime.
       */
      @java.lang.Override
      public long getLastUpdatetime() {
        return instance.getLastUpdatetime();
      }
      /**
       * <code>int64 LastUpdatetime = 7;</code>
       * @param value The lastUpdatetime to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdatetime(long value) {
        copyOnWrite();
        instance.setLastUpdatetime(value);
        return this;
      }
      /**
       * <code>int64 LastUpdatetime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdatetime() {
        copyOnWrite();
        instance.clearLastUpdatetime();
        return this;
      }

      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return The lastUpdateChapterName.
       */
      @java.lang.Override
      public java.lang.String getLastUpdateChapterName() {
        return instance.getLastUpdateChapterName();
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return The bytes for lastUpdateChapterName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLastUpdateChapterNameBytes() {
        return instance.getLastUpdateChapterNameBytes();
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @param value The lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterName(
          java.lang.String value) {
        copyOnWrite();
        instance.setLastUpdateChapterName(value);
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateChapterName() {
        copyOnWrite();
        instance.clearLastUpdateChapterName();
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 8;</code>
       * @param value The bytes for lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLastUpdateChapterNameBytes(value);
        return this;
      }

      /**
       * <code>string ComicPy = 9;</code>
       * @return The comicPy.
       */
      @java.lang.Override
      public java.lang.String getComicPy() {
        return instance.getComicPy();
      }
      /**
       * <code>string ComicPy = 9;</code>
       * @return The bytes for comicPy.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getComicPyBytes() {
        return instance.getComicPyBytes();
      }
      /**
       * <code>string ComicPy = 9;</code>
       * @param value The comicPy to set.
       * @return This builder for chaining.
       */
      public Builder setComicPy(
          java.lang.String value) {
        copyOnWrite();
        instance.setComicPy(value);
        return this;
      }
      /**
       * <code>string ComicPy = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearComicPy() {
        copyOnWrite();
        instance.clearComicPy();
        return this;
      }
      /**
       * <code>string ComicPy = 9;</code>
       * @param value The bytes for comicPy to set.
       * @return This builder for chaining.
       */
      public Builder setComicPyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setComicPyBytes(value);
        return this;
      }

      /**
       * <code>int32 Num = 10;</code>
       * @return The num.
       */
      @java.lang.Override
      public int getNum() {
        return instance.getNum();
      }
      /**
       * <code>int32 Num = 10;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {
        copyOnWrite();
        instance.setNum(value);
        return this;
      }
      /**
       * <code>int32 Num = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        copyOnWrite();
        instance.clearNum();
        return this;
      }

      /**
       * <code>int32 TagId = 11;</code>
       * @return The tagId.
       */
      @java.lang.Override
      public int getTagId() {
        return instance.getTagId();
      }
      /**
       * <code>int32 TagId = 11;</code>
       * @param value The tagId to set.
       * @return This builder for chaining.
       */
      public Builder setTagId(int value) {
        copyOnWrite();
        instance.setTagId(value);
        return this;
      }
      /**
       * <code>int32 TagId = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagId() {
        copyOnWrite();
        instance.clearTagId();
        return this;
      }

      /**
       * <code>string ChapterName = 12;</code>
       * @return The chapterName.
       */
      @java.lang.Override
      public java.lang.String getChapterName() {
        return instance.getChapterName();
      }
      /**
       * <code>string ChapterName = 12;</code>
       * @return The bytes for chapterName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getChapterNameBytes() {
        return instance.getChapterNameBytes();
      }
      /**
       * <code>string ChapterName = 12;</code>
       * @param value The chapterName to set.
       * @return This builder for chaining.
       */
      public Builder setChapterName(
          java.lang.String value) {
        copyOnWrite();
        instance.setChapterName(value);
        return this;
      }
      /**
       * <code>string ChapterName = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterName() {
        copyOnWrite();
        instance.clearChapterName();
        return this;
      }
      /**
       * <code>string ChapterName = 12;</code>
       * @param value The bytes for chapterName to set.
       * @return This builder for chaining.
       */
      public Builder setChapterNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChapterNameBytes(value);
        return this;
      }

      /**
       * <code>int32 ChapterId = 13;</code>
       * @return The chapterId.
       */
      @java.lang.Override
      public int getChapterId() {
        return instance.getChapterId();
      }
      /**
       * <code>int32 ChapterId = 13;</code>
       * @param value The chapterId to set.
       * @return This builder for chaining.
       */
      public Builder setChapterId(int value) {
        copyOnWrite();
        instance.setChapterId(value);
        return this;
      }
      /**
       * <code>int32 ChapterId = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterId() {
        copyOnWrite();
        instance.clearChapterId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.ComicRankListItemResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "comicId_",
              "title_",
              "authors_",
              "status_",
              "cover_",
              "types_",
              "lastUpdatetime_",
              "lastUpdateChapterName_",
              "comicPy_",
              "num_",
              "tagId_",
              "chapterName_",
              "chapterId_",
            };
            java.lang.String info =
                "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0000\u0000\u0001\u0004\u0002\u0208\u0003\u0208" +
                "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0002\b\u0208\t\u0208\n\u0004\u000b\u0004" +
                "\f\u0208\r\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.ComicRankListItemResponse)
    private static final com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse DEFAULT_INSTANCE;
    static {
      ComicRankListItemResponse defaultInstance = new ComicRankListItemResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ComicRankListItemResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.ComicRankListRes.ComicRankListItemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ComicRankListItemResponse> PARSER;

    public static com.google.protobuf.Parser<ComicRankListItemResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
