// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsListResponse.proto

package com.example.dmzj_api.pojo;

public final class NewsListRes {
  private NewsListRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NewsListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NewsListResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    int getErrno();

    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    java.lang.String getErrmsg();
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    java.util.List<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> 
        getDataList();
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse getData(int index);
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NewsListResponse}
   */
  public  static final class NewsListResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NewsListResponse, NewsListResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NewsListResponse)
      NewsListResponseOrBuilder {
    private NewsListResponse() {
      errmsg_ = "";
      data_ = emptyProtobufList();
    }
    public static final int ERRNO_FIELD_NUMBER = 1;
    private int errno_;
    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    @java.lang.Override
    public int getErrno() {
      return errno_;
    }
    /**
     * <code>int32 Errno = 1;</code>
     * @param value The errno to set.
     */
    private void setErrno(int value) {
      
      errno_ = value;
    }
    /**
     * <code>int32 Errno = 1;</code>
     */
    private void clearErrno() {
      
      errno_ = 0;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.String errmsg_;
    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    @java.lang.Override
    public java.lang.String getErrmsg() {
      return errmsg_;
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errmsg_);
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The errmsg to set.
     */
    private void setErrmsg(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      errmsg_ = value;
    }
    /**
     * <code>string Errmsg = 2;</code>
     */
    private void clearErrmsg() {
      
      errmsg_ = getDefaultInstance().getErrmsg();
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The bytes for errmsg to set.
     */
    private void setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errmsg_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> data_;
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    public java.util.List<? extends com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponseOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    public com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponseOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> tmp = data_;
      if (!tmp.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void setData(
        int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void addData(com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void addData(
        int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void addAllData(
        java.lang.Iterable<? extends com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NewsListRes.NewsListResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NewsListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NewsListRes.NewsListResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NewsListResponse)
        com.example.dmzj_api.pojo.NewsListRes.NewsListResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NewsListRes.NewsListResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 Errno = 1;</code>
       * @return The errno.
       */
      @java.lang.Override
      public int getErrno() {
        return instance.getErrno();
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @param value The errno to set.
       * @return This builder for chaining.
       */
      public Builder setErrno(int value) {
        copyOnWrite();
        instance.setErrno(value);
        return this;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrno() {
        copyOnWrite();
        instance.clearErrno();
        return this;
      }

      /**
       * <code>string Errmsg = 2;</code>
       * @return The errmsg.
       */
      @java.lang.Override
      public java.lang.String getErrmsg() {
        return instance.getErrmsg();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return The bytes for errmsg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        return instance.getErrmsgBytes();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrmsg(value);
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrmsg() {
        copyOnWrite();
        instance.clearErrmsg();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The bytes for errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrmsgBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse getData(int index) {
        return instance.getData(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder addData(com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder addData(
          com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NewsListItemResponse Data = 3;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NewsListResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NewsListRes.NewsListResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "errno_",
              "errmsg_",
              "data_",
              com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NewsListRes.NewsListResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NewsListRes.NewsListResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NewsListRes.NewsListResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NewsListResponse)
    private static final com.example.dmzj_api.pojo.NewsListRes.NewsListResponse DEFAULT_INSTANCE;
    static {
      NewsListResponse defaultInstance = new NewsListResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NewsListResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NewsListRes.NewsListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NewsListResponse> PARSER;

    public static com.google.protobuf.Parser<NewsListResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NewsListItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NewsListItemResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 ArticleId = 1;</code>
     * @return The articleId.
     */
    int getArticleId();

    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string FromName = 3;</code>
     * @return The fromName.
     */
    java.lang.String getFromName();
    /**
     * <code>string FromName = 3;</code>
     * @return The bytes for fromName.
     */
    com.google.protobuf.ByteString
        getFromNameBytes();

    /**
     * <code>string FromUrl = 4;</code>
     * @return The fromUrl.
     */
    java.lang.String getFromUrl();
    /**
     * <code>string FromUrl = 4;</code>
     * @return The bytes for fromUrl.
     */
    com.google.protobuf.ByteString
        getFromUrlBytes();

    /**
     * <code>int64 CreateTime = 5;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>int32 IsForeign = 6;</code>
     * @return The isForeign.
     */
    int getIsForeign();

    /**
     * <code>string ForeignUrl = 7;</code>
     * @return The foreignUrl.
     */
    java.lang.String getForeignUrl();
    /**
     * <code>string ForeignUrl = 7;</code>
     * @return The bytes for foreignUrl.
     */
    com.google.protobuf.ByteString
        getForeignUrlBytes();

    /**
     * <code>string Intro = 8;</code>
     * @return The intro.
     */
    java.lang.String getIntro();
    /**
     * <code>string Intro = 8;</code>
     * @return The bytes for intro.
     */
    com.google.protobuf.ByteString
        getIntroBytes();

    /**
     * <code>int32 AuthorId = 9;</code>
     * @return The authorId.
     */
    int getAuthorId();

    /**
     * <code>int32 Status = 10;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string RowPicUrl = 11;</code>
     * @return The rowPicUrl.
     */
    java.lang.String getRowPicUrl();
    /**
     * <code>string RowPicUrl = 11;</code>
     * @return The bytes for rowPicUrl.
     */
    com.google.protobuf.ByteString
        getRowPicUrlBytes();

    /**
     * <code>string ColPicUrl = 12;</code>
     * @return The colPicUrl.
     */
    java.lang.String getColPicUrl();
    /**
     * <code>string ColPicUrl = 12;</code>
     * @return The bytes for colPicUrl.
     */
    com.google.protobuf.ByteString
        getColPicUrlBytes();

    /**
     * <code>int32 QchatShow = 13;</code>
     * @return The qchatShow.
     */
    int getQchatShow();

    /**
     * <code>string PageUrl = 14;</code>
     * @return The pageUrl.
     */
    java.lang.String getPageUrl();
    /**
     * <code>string PageUrl = 14;</code>
     * @return The bytes for pageUrl.
     */
    com.google.protobuf.ByteString
        getPageUrlBytes();

    /**
     * <code>int32 CommentAmount = 15;</code>
     * @return The commentAmount.
     */
    int getCommentAmount();

    /**
     * <code>int32 AuthorUid = 16;</code>
     * @return The authorUid.
     */
    int getAuthorUid();

    /**
     * <code>string Cover = 17;</code>
     * @return The cover.
     */
    java.lang.String getCover();
    /**
     * <code>string Cover = 17;</code>
     * @return The bytes for cover.
     */
    com.google.protobuf.ByteString
        getCoverBytes();

    /**
     * <code>string Nickname = 18;</code>
     * @return The nickname.
     */
    java.lang.String getNickname();
    /**
     * <code>string Nickname = 18;</code>
     * @return The bytes for nickname.
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>int32 MoodAmount = 19;</code>
     * @return The moodAmount.
     */
    int getMoodAmount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NewsListItemResponse}
   */
  public  static final class NewsListItemResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NewsListItemResponse, NewsListItemResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NewsListItemResponse)
      NewsListItemResponseOrBuilder {
    private NewsListItemResponse() {
      title_ = "";
      fromName_ = "";
      fromUrl_ = "";
      foreignUrl_ = "";
      intro_ = "";
      rowPicUrl_ = "";
      colPicUrl_ = "";
      pageUrl_ = "";
      cover_ = "";
      nickname_ = "";
    }
    public static final int ARTICLEID_FIELD_NUMBER = 1;
    private int articleId_;
    /**
     * <code>int32 ArticleId = 1;</code>
     * @return The articleId.
     */
    @java.lang.Override
    public int getArticleId() {
      return articleId_;
    }
    /**
     * <code>int32 ArticleId = 1;</code>
     * @param value The articleId to set.
     */
    private void setArticleId(int value) {
      
      articleId_ = value;
    }
    /**
     * <code>int32 ArticleId = 1;</code>
     */
    private void clearArticleId() {
      
      articleId_ = 0;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.String title_;
    /**
     * <code>string Title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>string Title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>string Title = 2;</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      title_ = value;
    }
    /**
     * <code>string Title = 2;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>string Title = 2;</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();
      
    }

    public static final int FROMNAME_FIELD_NUMBER = 3;
    private java.lang.String fromName_;
    /**
     * <code>string FromName = 3;</code>
     * @return The fromName.
     */
    @java.lang.Override
    public java.lang.String getFromName() {
      return fromName_;
    }
    /**
     * <code>string FromName = 3;</code>
     * @return The bytes for fromName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fromName_);
    }
    /**
     * <code>string FromName = 3;</code>
     * @param value The fromName to set.
     */
    private void setFromName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fromName_ = value;
    }
    /**
     * <code>string FromName = 3;</code>
     */
    private void clearFromName() {
      
      fromName_ = getDefaultInstance().getFromName();
    }
    /**
     * <code>string FromName = 3;</code>
     * @param value The bytes for fromName to set.
     */
    private void setFromNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fromName_ = value.toStringUtf8();
      
    }

    public static final int FROMURL_FIELD_NUMBER = 4;
    private java.lang.String fromUrl_;
    /**
     * <code>string FromUrl = 4;</code>
     * @return The fromUrl.
     */
    @java.lang.Override
    public java.lang.String getFromUrl() {
      return fromUrl_;
    }
    /**
     * <code>string FromUrl = 4;</code>
     * @return The bytes for fromUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fromUrl_);
    }
    /**
     * <code>string FromUrl = 4;</code>
     * @param value The fromUrl to set.
     */
    private void setFromUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fromUrl_ = value;
    }
    /**
     * <code>string FromUrl = 4;</code>
     */
    private void clearFromUrl() {
      
      fromUrl_ = getDefaultInstance().getFromUrl();
    }
    /**
     * <code>string FromUrl = 4;</code>
     * @param value The bytes for fromUrl to set.
     */
    private void setFromUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fromUrl_ = value.toStringUtf8();
      
    }

    public static final int CREATETIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <code>int64 CreateTime = 5;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <code>int64 CreateTime = 5;</code>
     * @param value The createTime to set.
     */
    private void setCreateTime(long value) {
      
      createTime_ = value;
    }
    /**
     * <code>int64 CreateTime = 5;</code>
     */
    private void clearCreateTime() {
      
      createTime_ = 0L;
    }

    public static final int ISFOREIGN_FIELD_NUMBER = 6;
    private int isForeign_;
    /**
     * <code>int32 IsForeign = 6;</code>
     * @return The isForeign.
     */
    @java.lang.Override
    public int getIsForeign() {
      return isForeign_;
    }
    /**
     * <code>int32 IsForeign = 6;</code>
     * @param value The isForeign to set.
     */
    private void setIsForeign(int value) {
      
      isForeign_ = value;
    }
    /**
     * <code>int32 IsForeign = 6;</code>
     */
    private void clearIsForeign() {
      
      isForeign_ = 0;
    }

    public static final int FOREIGNURL_FIELD_NUMBER = 7;
    private java.lang.String foreignUrl_;
    /**
     * <code>string ForeignUrl = 7;</code>
     * @return The foreignUrl.
     */
    @java.lang.Override
    public java.lang.String getForeignUrl() {
      return foreignUrl_;
    }
    /**
     * <code>string ForeignUrl = 7;</code>
     * @return The bytes for foreignUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getForeignUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(foreignUrl_);
    }
    /**
     * <code>string ForeignUrl = 7;</code>
     * @param value The foreignUrl to set.
     */
    private void setForeignUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      foreignUrl_ = value;
    }
    /**
     * <code>string ForeignUrl = 7;</code>
     */
    private void clearForeignUrl() {
      
      foreignUrl_ = getDefaultInstance().getForeignUrl();
    }
    /**
     * <code>string ForeignUrl = 7;</code>
     * @param value The bytes for foreignUrl to set.
     */
    private void setForeignUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      foreignUrl_ = value.toStringUtf8();
      
    }

    public static final int INTRO_FIELD_NUMBER = 8;
    private java.lang.String intro_;
    /**
     * <code>string Intro = 8;</code>
     * @return The intro.
     */
    @java.lang.Override
    public java.lang.String getIntro() {
      return intro_;
    }
    /**
     * <code>string Intro = 8;</code>
     * @return The bytes for intro.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIntroBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(intro_);
    }
    /**
     * <code>string Intro = 8;</code>
     * @param value The intro to set.
     */
    private void setIntro(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      intro_ = value;
    }
    /**
     * <code>string Intro = 8;</code>
     */
    private void clearIntro() {
      
      intro_ = getDefaultInstance().getIntro();
    }
    /**
     * <code>string Intro = 8;</code>
     * @param value The bytes for intro to set.
     */
    private void setIntroBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      intro_ = value.toStringUtf8();
      
    }

    public static final int AUTHORID_FIELD_NUMBER = 9;
    private int authorId_;
    /**
     * <code>int32 AuthorId = 9;</code>
     * @return The authorId.
     */
    @java.lang.Override
    public int getAuthorId() {
      return authorId_;
    }
    /**
     * <code>int32 AuthorId = 9;</code>
     * @param value The authorId to set.
     */
    private void setAuthorId(int value) {
      
      authorId_ = value;
    }
    /**
     * <code>int32 AuthorId = 9;</code>
     */
    private void clearAuthorId() {
      
      authorId_ = 0;
    }

    public static final int STATUS_FIELD_NUMBER = 10;
    private int status_;
    /**
     * <code>int32 Status = 10;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 Status = 10;</code>
     * @param value The status to set.
     */
    private void setStatus(int value) {
      
      status_ = value;
    }
    /**
     * <code>int32 Status = 10;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int ROWPICURL_FIELD_NUMBER = 11;
    private java.lang.String rowPicUrl_;
    /**
     * <code>string RowPicUrl = 11;</code>
     * @return The rowPicUrl.
     */
    @java.lang.Override
    public java.lang.String getRowPicUrl() {
      return rowPicUrl_;
    }
    /**
     * <code>string RowPicUrl = 11;</code>
     * @return The bytes for rowPicUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRowPicUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(rowPicUrl_);
    }
    /**
     * <code>string RowPicUrl = 11;</code>
     * @param value The rowPicUrl to set.
     */
    private void setRowPicUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      rowPicUrl_ = value;
    }
    /**
     * <code>string RowPicUrl = 11;</code>
     */
    private void clearRowPicUrl() {
      
      rowPicUrl_ = getDefaultInstance().getRowPicUrl();
    }
    /**
     * <code>string RowPicUrl = 11;</code>
     * @param value The bytes for rowPicUrl to set.
     */
    private void setRowPicUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      rowPicUrl_ = value.toStringUtf8();
      
    }

    public static final int COLPICURL_FIELD_NUMBER = 12;
    private java.lang.String colPicUrl_;
    /**
     * <code>string ColPicUrl = 12;</code>
     * @return The colPicUrl.
     */
    @java.lang.Override
    public java.lang.String getColPicUrl() {
      return colPicUrl_;
    }
    /**
     * <code>string ColPicUrl = 12;</code>
     * @return The bytes for colPicUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColPicUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(colPicUrl_);
    }
    /**
     * <code>string ColPicUrl = 12;</code>
     * @param value The colPicUrl to set.
     */
    private void setColPicUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      colPicUrl_ = value;
    }
    /**
     * <code>string ColPicUrl = 12;</code>
     */
    private void clearColPicUrl() {
      
      colPicUrl_ = getDefaultInstance().getColPicUrl();
    }
    /**
     * <code>string ColPicUrl = 12;</code>
     * @param value The bytes for colPicUrl to set.
     */
    private void setColPicUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      colPicUrl_ = value.toStringUtf8();
      
    }

    public static final int QCHATSHOW_FIELD_NUMBER = 13;
    private int qchatShow_;
    /**
     * <code>int32 QchatShow = 13;</code>
     * @return The qchatShow.
     */
    @java.lang.Override
    public int getQchatShow() {
      return qchatShow_;
    }
    /**
     * <code>int32 QchatShow = 13;</code>
     * @param value The qchatShow to set.
     */
    private void setQchatShow(int value) {
      
      qchatShow_ = value;
    }
    /**
     * <code>int32 QchatShow = 13;</code>
     */
    private void clearQchatShow() {
      
      qchatShow_ = 0;
    }

    public static final int PAGEURL_FIELD_NUMBER = 14;
    private java.lang.String pageUrl_;
    /**
     * <code>string PageUrl = 14;</code>
     * @return The pageUrl.
     */
    @java.lang.Override
    public java.lang.String getPageUrl() {
      return pageUrl_;
    }
    /**
     * <code>string PageUrl = 14;</code>
     * @return The bytes for pageUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPageUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pageUrl_);
    }
    /**
     * <code>string PageUrl = 14;</code>
     * @param value The pageUrl to set.
     */
    private void setPageUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      pageUrl_ = value;
    }
    /**
     * <code>string PageUrl = 14;</code>
     */
    private void clearPageUrl() {
      
      pageUrl_ = getDefaultInstance().getPageUrl();
    }
    /**
     * <code>string PageUrl = 14;</code>
     * @param value The bytes for pageUrl to set.
     */
    private void setPageUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      pageUrl_ = value.toStringUtf8();
      
    }

    public static final int COMMENTAMOUNT_FIELD_NUMBER = 15;
    private int commentAmount_;
    /**
     * <code>int32 CommentAmount = 15;</code>
     * @return The commentAmount.
     */
    @java.lang.Override
    public int getCommentAmount() {
      return commentAmount_;
    }
    /**
     * <code>int32 CommentAmount = 15;</code>
     * @param value The commentAmount to set.
     */
    private void setCommentAmount(int value) {
      
      commentAmount_ = value;
    }
    /**
     * <code>int32 CommentAmount = 15;</code>
     */
    private void clearCommentAmount() {
      
      commentAmount_ = 0;
    }

    public static final int AUTHORUID_FIELD_NUMBER = 16;
    private int authorUid_;
    /**
     * <code>int32 AuthorUid = 16;</code>
     * @return The authorUid.
     */
    @java.lang.Override
    public int getAuthorUid() {
      return authorUid_;
    }
    /**
     * <code>int32 AuthorUid = 16;</code>
     * @param value The authorUid to set.
     */
    private void setAuthorUid(int value) {
      
      authorUid_ = value;
    }
    /**
     * <code>int32 AuthorUid = 16;</code>
     */
    private void clearAuthorUid() {
      
      authorUid_ = 0;
    }

    public static final int COVER_FIELD_NUMBER = 17;
    private java.lang.String cover_;
    /**
     * <code>string Cover = 17;</code>
     * @return The cover.
     */
    @java.lang.Override
    public java.lang.String getCover() {
      return cover_;
    }
    /**
     * <code>string Cover = 17;</code>
     * @return The bytes for cover.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoverBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cover_);
    }
    /**
     * <code>string Cover = 17;</code>
     * @param value The cover to set.
     */
    private void setCover(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      cover_ = value;
    }
    /**
     * <code>string Cover = 17;</code>
     */
    private void clearCover() {
      
      cover_ = getDefaultInstance().getCover();
    }
    /**
     * <code>string Cover = 17;</code>
     * @param value The bytes for cover to set.
     */
    private void setCoverBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cover_ = value.toStringUtf8();
      
    }

    public static final int NICKNAME_FIELD_NUMBER = 18;
    private java.lang.String nickname_;
    /**
     * <code>string Nickname = 18;</code>
     * @return The nickname.
     */
    @java.lang.Override
    public java.lang.String getNickname() {
      return nickname_;
    }
    /**
     * <code>string Nickname = 18;</code>
     * @return The bytes for nickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nickname_);
    }
    /**
     * <code>string Nickname = 18;</code>
     * @param value The nickname to set.
     */
    private void setNickname(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      nickname_ = value;
    }
    /**
     * <code>string Nickname = 18;</code>
     */
    private void clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
    }
    /**
     * <code>string Nickname = 18;</code>
     * @param value The bytes for nickname to set.
     */
    private void setNicknameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      nickname_ = value.toStringUtf8();
      
    }

    public static final int MOODAMOUNT_FIELD_NUMBER = 19;
    private int moodAmount_;
    /**
     * <code>int32 MoodAmount = 19;</code>
     * @return The moodAmount.
     */
    @java.lang.Override
    public int getMoodAmount() {
      return moodAmount_;
    }
    /**
     * <code>int32 MoodAmount = 19;</code>
     * @param value The moodAmount to set.
     */
    private void setMoodAmount(int value) {
      
      moodAmount_ = value;
    }
    /**
     * <code>int32 MoodAmount = 19;</code>
     */
    private void clearMoodAmount() {
      
      moodAmount_ = 0;
    }

    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NewsListItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NewsListItemResponse)
        com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 ArticleId = 1;</code>
       * @return The articleId.
       */
      @java.lang.Override
      public int getArticleId() {
        return instance.getArticleId();
      }
      /**
       * <code>int32 ArticleId = 1;</code>
       * @param value The articleId to set.
       * @return This builder for chaining.
       */
      public Builder setArticleId(int value) {
        copyOnWrite();
        instance.setArticleId(value);
        return this;
      }
      /**
       * <code>int32 ArticleId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearArticleId() {
        copyOnWrite();
        instance.clearArticleId();
        return this;
      }

      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>string Title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>string FromName = 3;</code>
       * @return The fromName.
       */
      @java.lang.Override
      public java.lang.String getFromName() {
        return instance.getFromName();
      }
      /**
       * <code>string FromName = 3;</code>
       * @return The bytes for fromName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFromNameBytes() {
        return instance.getFromNameBytes();
      }
      /**
       * <code>string FromName = 3;</code>
       * @param value The fromName to set.
       * @return This builder for chaining.
       */
      public Builder setFromName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFromName(value);
        return this;
      }
      /**
       * <code>string FromName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromName() {
        copyOnWrite();
        instance.clearFromName();
        return this;
      }
      /**
       * <code>string FromName = 3;</code>
       * @param value The bytes for fromName to set.
       * @return This builder for chaining.
       */
      public Builder setFromNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromNameBytes(value);
        return this;
      }

      /**
       * <code>string FromUrl = 4;</code>
       * @return The fromUrl.
       */
      @java.lang.Override
      public java.lang.String getFromUrl() {
        return instance.getFromUrl();
      }
      /**
       * <code>string FromUrl = 4;</code>
       * @return The bytes for fromUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFromUrlBytes() {
        return instance.getFromUrlBytes();
      }
      /**
       * <code>string FromUrl = 4;</code>
       * @param value The fromUrl to set.
       * @return This builder for chaining.
       */
      public Builder setFromUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setFromUrl(value);
        return this;
      }
      /**
       * <code>string FromUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUrl() {
        copyOnWrite();
        instance.clearFromUrl();
        return this;
      }
      /**
       * <code>string FromUrl = 4;</code>
       * @param value The bytes for fromUrl to set.
       * @return This builder for chaining.
       */
      public Builder setFromUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromUrlBytes(value);
        return this;
      }

      /**
       * <code>int64 CreateTime = 5;</code>
       * @return The createTime.
       */
      @java.lang.Override
      public long getCreateTime() {
        return instance.getCreateTime();
      }
      /**
       * <code>int64 CreateTime = 5;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        copyOnWrite();
        instance.setCreateTime(value);
        return this;
      }
      /**
       * <code>int64 CreateTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        copyOnWrite();
        instance.clearCreateTime();
        return this;
      }

      /**
       * <code>int32 IsForeign = 6;</code>
       * @return The isForeign.
       */
      @java.lang.Override
      public int getIsForeign() {
        return instance.getIsForeign();
      }
      /**
       * <code>int32 IsForeign = 6;</code>
       * @param value The isForeign to set.
       * @return This builder for chaining.
       */
      public Builder setIsForeign(int value) {
        copyOnWrite();
        instance.setIsForeign(value);
        return this;
      }
      /**
       * <code>int32 IsForeign = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsForeign() {
        copyOnWrite();
        instance.clearIsForeign();
        return this;
      }

      /**
       * <code>string ForeignUrl = 7;</code>
       * @return The foreignUrl.
       */
      @java.lang.Override
      public java.lang.String getForeignUrl() {
        return instance.getForeignUrl();
      }
      /**
       * <code>string ForeignUrl = 7;</code>
       * @return The bytes for foreignUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getForeignUrlBytes() {
        return instance.getForeignUrlBytes();
      }
      /**
       * <code>string ForeignUrl = 7;</code>
       * @param value The foreignUrl to set.
       * @return This builder for chaining.
       */
      public Builder setForeignUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setForeignUrl(value);
        return this;
      }
      /**
       * <code>string ForeignUrl = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearForeignUrl() {
        copyOnWrite();
        instance.clearForeignUrl();
        return this;
      }
      /**
       * <code>string ForeignUrl = 7;</code>
       * @param value The bytes for foreignUrl to set.
       * @return This builder for chaining.
       */
      public Builder setForeignUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setForeignUrlBytes(value);
        return this;
      }

      /**
       * <code>string Intro = 8;</code>
       * @return The intro.
       */
      @java.lang.Override
      public java.lang.String getIntro() {
        return instance.getIntro();
      }
      /**
       * <code>string Intro = 8;</code>
       * @return The bytes for intro.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIntroBytes() {
        return instance.getIntroBytes();
      }
      /**
       * <code>string Intro = 8;</code>
       * @param value The intro to set.
       * @return This builder for chaining.
       */
      public Builder setIntro(
          java.lang.String value) {
        copyOnWrite();
        instance.setIntro(value);
        return this;
      }
      /**
       * <code>string Intro = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntro() {
        copyOnWrite();
        instance.clearIntro();
        return this;
      }
      /**
       * <code>string Intro = 8;</code>
       * @param value The bytes for intro to set.
       * @return This builder for chaining.
       */
      public Builder setIntroBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIntroBytes(value);
        return this;
      }

      /**
       * <code>int32 AuthorId = 9;</code>
       * @return The authorId.
       */
      @java.lang.Override
      public int getAuthorId() {
        return instance.getAuthorId();
      }
      /**
       * <code>int32 AuthorId = 9;</code>
       * @param value The authorId to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorId(int value) {
        copyOnWrite();
        instance.setAuthorId(value);
        return this;
      }
      /**
       * <code>int32 AuthorId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorId() {
        copyOnWrite();
        instance.clearAuthorId();
        return this;
      }

      /**
       * <code>int32 Status = 10;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>int32 Status = 10;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>int32 Status = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>string RowPicUrl = 11;</code>
       * @return The rowPicUrl.
       */
      @java.lang.Override
      public java.lang.String getRowPicUrl() {
        return instance.getRowPicUrl();
      }
      /**
       * <code>string RowPicUrl = 11;</code>
       * @return The bytes for rowPicUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRowPicUrlBytes() {
        return instance.getRowPicUrlBytes();
      }
      /**
       * <code>string RowPicUrl = 11;</code>
       * @param value The rowPicUrl to set.
       * @return This builder for chaining.
       */
      public Builder setRowPicUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setRowPicUrl(value);
        return this;
      }
      /**
       * <code>string RowPicUrl = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearRowPicUrl() {
        copyOnWrite();
        instance.clearRowPicUrl();
        return this;
      }
      /**
       * <code>string RowPicUrl = 11;</code>
       * @param value The bytes for rowPicUrl to set.
       * @return This builder for chaining.
       */
      public Builder setRowPicUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRowPicUrlBytes(value);
        return this;
      }

      /**
       * <code>string ColPicUrl = 12;</code>
       * @return The colPicUrl.
       */
      @java.lang.Override
      public java.lang.String getColPicUrl() {
        return instance.getColPicUrl();
      }
      /**
       * <code>string ColPicUrl = 12;</code>
       * @return The bytes for colPicUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getColPicUrlBytes() {
        return instance.getColPicUrlBytes();
      }
      /**
       * <code>string ColPicUrl = 12;</code>
       * @param value The colPicUrl to set.
       * @return This builder for chaining.
       */
      public Builder setColPicUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setColPicUrl(value);
        return this;
      }
      /**
       * <code>string ColPicUrl = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearColPicUrl() {
        copyOnWrite();
        instance.clearColPicUrl();
        return this;
      }
      /**
       * <code>string ColPicUrl = 12;</code>
       * @param value The bytes for colPicUrl to set.
       * @return This builder for chaining.
       */
      public Builder setColPicUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setColPicUrlBytes(value);
        return this;
      }

      /**
       * <code>int32 QchatShow = 13;</code>
       * @return The qchatShow.
       */
      @java.lang.Override
      public int getQchatShow() {
        return instance.getQchatShow();
      }
      /**
       * <code>int32 QchatShow = 13;</code>
       * @param value The qchatShow to set.
       * @return This builder for chaining.
       */
      public Builder setQchatShow(int value) {
        copyOnWrite();
        instance.setQchatShow(value);
        return this;
      }
      /**
       * <code>int32 QchatShow = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearQchatShow() {
        copyOnWrite();
        instance.clearQchatShow();
        return this;
      }

      /**
       * <code>string PageUrl = 14;</code>
       * @return The pageUrl.
       */
      @java.lang.Override
      public java.lang.String getPageUrl() {
        return instance.getPageUrl();
      }
      /**
       * <code>string PageUrl = 14;</code>
       * @return The bytes for pageUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPageUrlBytes() {
        return instance.getPageUrlBytes();
      }
      /**
       * <code>string PageUrl = 14;</code>
       * @param value The pageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPageUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setPageUrl(value);
        return this;
      }
      /**
       * <code>string PageUrl = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageUrl() {
        copyOnWrite();
        instance.clearPageUrl();
        return this;
      }
      /**
       * <code>string PageUrl = 14;</code>
       * @param value The bytes for pageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPageUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPageUrlBytes(value);
        return this;
      }

      /**
       * <code>int32 CommentAmount = 15;</code>
       * @return The commentAmount.
       */
      @java.lang.Override
      public int getCommentAmount() {
        return instance.getCommentAmount();
      }
      /**
       * <code>int32 CommentAmount = 15;</code>
       * @param value The commentAmount to set.
       * @return This builder for chaining.
       */
      public Builder setCommentAmount(int value) {
        copyOnWrite();
        instance.setCommentAmount(value);
        return this;
      }
      /**
       * <code>int32 CommentAmount = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommentAmount() {
        copyOnWrite();
        instance.clearCommentAmount();
        return this;
      }

      /**
       * <code>int32 AuthorUid = 16;</code>
       * @return The authorUid.
       */
      @java.lang.Override
      public int getAuthorUid() {
        return instance.getAuthorUid();
      }
      /**
       * <code>int32 AuthorUid = 16;</code>
       * @param value The authorUid to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorUid(int value) {
        copyOnWrite();
        instance.setAuthorUid(value);
        return this;
      }
      /**
       * <code>int32 AuthorUid = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorUid() {
        copyOnWrite();
        instance.clearAuthorUid();
        return this;
      }

      /**
       * <code>string Cover = 17;</code>
       * @return The cover.
       */
      @java.lang.Override
      public java.lang.String getCover() {
        return instance.getCover();
      }
      /**
       * <code>string Cover = 17;</code>
       * @return The bytes for cover.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCoverBytes() {
        return instance.getCoverBytes();
      }
      /**
       * <code>string Cover = 17;</code>
       * @param value The cover to set.
       * @return This builder for chaining.
       */
      public Builder setCover(
          java.lang.String value) {
        copyOnWrite();
        instance.setCover(value);
        return this;
      }
      /**
       * <code>string Cover = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearCover() {
        copyOnWrite();
        instance.clearCover();
        return this;
      }
      /**
       * <code>string Cover = 17;</code>
       * @param value The bytes for cover to set.
       * @return This builder for chaining.
       */
      public Builder setCoverBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCoverBytes(value);
        return this;
      }

      /**
       * <code>string Nickname = 18;</code>
       * @return The nickname.
       */
      @java.lang.Override
      public java.lang.String getNickname() {
        return instance.getNickname();
      }
      /**
       * <code>string Nickname = 18;</code>
       * @return The bytes for nickname.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        return instance.getNicknameBytes();
      }
      /**
       * <code>string Nickname = 18;</code>
       * @param value The nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNickname(
          java.lang.String value) {
        copyOnWrite();
        instance.setNickname(value);
        return this;
      }
      /**
       * <code>string Nickname = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearNickname() {
        copyOnWrite();
        instance.clearNickname();
        return this;
      }
      /**
       * <code>string Nickname = 18;</code>
       * @param value The bytes for nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNicknameBytes(value);
        return this;
      }

      /**
       * <code>int32 MoodAmount = 19;</code>
       * @return The moodAmount.
       */
      @java.lang.Override
      public int getMoodAmount() {
        return instance.getMoodAmount();
      }
      /**
       * <code>int32 MoodAmount = 19;</code>
       * @param value The moodAmount to set.
       * @return This builder for chaining.
       */
      public Builder setMoodAmount(int value) {
        copyOnWrite();
        instance.setMoodAmount(value);
        return this;
      }
      /**
       * <code>int32 MoodAmount = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoodAmount() {
        copyOnWrite();
        instance.clearMoodAmount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NewsListItemResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "articleId_",
              "title_",
              "fromName_",
              "fromUrl_",
              "createTime_",
              "isForeign_",
              "foreignUrl_",
              "intro_",
              "authorId_",
              "status_",
              "rowPicUrl_",
              "colPicUrl_",
              "qchatShow_",
              "pageUrl_",
              "commentAmount_",
              "authorUid_",
              "cover_",
              "nickname_",
              "moodAmount_",
            };
            java.lang.String info =
                "\u0000\u0013\u0000\u0000\u0001\u0013\u0013\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0002\u0006\u0004\u0007\u0208\b\u0208\t\u0004\n\u0004" +
                "\u000b\u0208\f\u0208\r\u0004\u000e\u0208\u000f\u0004\u0010\u0004\u0011\u0208\u0012" +
                "\u0208\u0013\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NewsListItemResponse)
    private static final com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse DEFAULT_INSTANCE;
    static {
      NewsListItemResponse defaultInstance = new NewsListItemResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NewsListItemResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NewsListRes.NewsListItemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NewsListItemResponse> PARSER;

    public static com.google.protobuf.Parser<NewsListItemResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
