// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NovelDetailResponse.proto

package com.example.dmzj_api.pojo;

public final class NovelDetailRes {
  private NovelDetailRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NovelDetailResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelDetailResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    int getErrno();

    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    java.lang.String getErrmsg();
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     * @return The data.
     */
    com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse getData();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailResponse}
   */
  public  static final class NovelDetailResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelDetailResponse, NovelDetailResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelDetailResponse)
      NovelDetailResponseOrBuilder {
    private NovelDetailResponse() {
      errmsg_ = "";
    }
    public static final int ERRNO_FIELD_NUMBER = 1;
    private int errno_;
    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    @java.lang.Override
    public int getErrno() {
      return errno_;
    }
    /**
     * <code>int32 Errno = 1;</code>
     * @param value The errno to set.
     */
    private void setErrno(int value) {
      
      errno_ = value;
    }
    /**
     * <code>int32 Errno = 1;</code>
     */
    private void clearErrno() {
      
      errno_ = 0;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.String errmsg_;
    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    @java.lang.Override
    public java.lang.String getErrmsg() {
      return errmsg_;
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errmsg_);
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The errmsg to set.
     */
    private void setErrmsg(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      errmsg_ = value;
    }
    /**
     * <code>string Errmsg = 2;</code>
     */
    private void clearErrmsg() {
      
      errmsg_ = getDefaultInstance().getErrmsg();
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The bytes for errmsg to set.
     */
    private void setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errmsg_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse data_;
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse getData() {
      return data_ == null ? com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.getDefaultInstance() : data_;
    }
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     */
    private void setData(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse value) {
      value.getClass();
  data_ = value;
      
      }
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeData(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse value) {
      value.getClass();
  if (data_ != null &&
          data_ != com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.getDefaultInstance()) {
        data_ =
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.newBuilder(data_).mergeFrom(value).buildPartial();
      } else {
        data_ = value;
      }
      
    }
    /**
     * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
     */
    private void clearData() {  data_ = null;
      
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelDetailResponse)
        com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 Errno = 1;</code>
       * @return The errno.
       */
      @java.lang.Override
      public int getErrno() {
        return instance.getErrno();
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @param value The errno to set.
       * @return This builder for chaining.
       */
      public Builder setErrno(int value) {
        copyOnWrite();
        instance.setErrno(value);
        return this;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrno() {
        copyOnWrite();
        instance.clearErrno();
        return this;
      }

      /**
       * <code>string Errmsg = 2;</code>
       * @return The errmsg.
       */
      @java.lang.Override
      public java.lang.String getErrmsg() {
        return instance.getErrmsg();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return The bytes for errmsg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        return instance.getErrmsgBytes();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrmsg(value);
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrmsg() {
        copyOnWrite();
        instance.clearErrmsg();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The bytes for errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrmsgBytes(value);
        return this;
      }

      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse getData() {
        return instance.getData();
      }
      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      public Builder setData(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse value) {
        copyOnWrite();
        instance.setData(value);
        return this;
        }
      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      public Builder setData(
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      public Builder mergeData(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.com.example.dmzj_api.pojo.NovelDetailInfoResponse Data = 3;</code>
       */
      public Builder clearData() {  copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelDetailResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "errno_",
              "errmsg_",
              "data_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelDetailResponse)
    private static final com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse DEFAULT_INSTANCE;
    static {
      NovelDetailResponse defaultInstance = new NovelDetailResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelDetailResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelDetailResponse> PARSER;

    public static com.google.protobuf.Parser<NovelDetailResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NovelDetailInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelDetailInfoResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 NovelId = 1;</code>
     * @return The novelId.
     */
    int getNovelId();

    /**
     * <code>string Name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string Zone = 3;</code>
     * @return The zone.
     */
    java.lang.String getZone();
    /**
     * <code>string Zone = 3;</code>
     * @return The bytes for zone.
     */
    com.google.protobuf.ByteString
        getZoneBytes();

    /**
     * <code>string Status = 4;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string Status = 4;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @return The lastUpdateVolumeName.
     */
    java.lang.String getLastUpdateVolumeName();
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @return The bytes for lastUpdateVolumeName.
     */
    com.google.protobuf.ByteString
        getLastUpdateVolumeNameBytes();

    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @return The lastUpdateChapterName.
     */
    java.lang.String getLastUpdateChapterName();
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes();

    /**
     * <code>int32 LastUpdateVolumeId = 7;</code>
     * @return The lastUpdateVolumeId.
     */
    int getLastUpdateVolumeId();

    /**
     * <code>int32 LastUpdateChapterId = 8;</code>
     * @return The lastUpdateChapterId.
     */
    int getLastUpdateChapterId();

    /**
     * <code>int64 LastUpdateTime = 9;</code>
     * @return The lastUpdateTime.
     */
    long getLastUpdateTime();

    /**
     * <code>string Cover = 10;</code>
     * @return The cover.
     */
    java.lang.String getCover();
    /**
     * <code>string Cover = 10;</code>
     * @return The bytes for cover.
     */
    com.google.protobuf.ByteString
        getCoverBytes();

    /**
     * <code>int32 HotHits = 11;</code>
     * @return The hotHits.
     */
    int getHotHits();

    /**
     * <code>string Introduction = 12;</code>
     * @return The introduction.
     */
    java.lang.String getIntroduction();
    /**
     * <code>string Introduction = 12;</code>
     * @return The bytes for introduction.
     */
    com.google.protobuf.ByteString
        getIntroductionBytes();

    /**
     * <code>repeated string Types = 13;</code>
     * @return A list containing the types.
     */
    java.util.List<java.lang.String>
        getTypesList();
    /**
     * <code>repeated string Types = 13;</code>
     * @return The count of types.
     */
    int getTypesCount();
    /**
     * <code>repeated string Types = 13;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    java.lang.String getTypes(int index);
    /**
     * <code>repeated string Types = 13;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    com.google.protobuf.ByteString
        getTypesBytes(int index);

    /**
     * <code>string Authors = 14;</code>
     * @return The authors.
     */
    java.lang.String getAuthors();
    /**
     * <code>string Authors = 14;</code>
     * @return The bytes for authors.
     */
    com.google.protobuf.ByteString
        getAuthorsBytes();

    /**
     * <code>string FirstLetter = 15;</code>
     * @return The firstLetter.
     */
    java.lang.String getFirstLetter();
    /**
     * <code>string FirstLetter = 15;</code>
     * @return The bytes for firstLetter.
     */
    com.google.protobuf.ByteString
        getFirstLetterBytes();

    /**
     * <code>int32 SubscribeNum = 16;</code>
     * @return The subscribeNum.
     */
    int getSubscribeNum();

    /**
     * <code>int64 RedisUpdateTime = 17;</code>
     * @return The redisUpdateTime.
     */
    long getRedisUpdateTime();

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    java.util.List<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> 
        getVolumeList();
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse getVolume(int index);
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    int getVolumeCount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailInfoResponse}
   */
  public  static final class NovelDetailInfoResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelDetailInfoResponse, NovelDetailInfoResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelDetailInfoResponse)
      NovelDetailInfoResponseOrBuilder {
    private NovelDetailInfoResponse() {
      name_ = "";
      zone_ = "";
      status_ = "";
      lastUpdateVolumeName_ = "";
      lastUpdateChapterName_ = "";
      cover_ = "";
      introduction_ = "";
      types_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      authors_ = "";
      firstLetter_ = "";
      volume_ = emptyProtobufList();
    }
    public static final int NOVELID_FIELD_NUMBER = 1;
    private int novelId_;
    /**
     * <code>int32 NovelId = 1;</code>
     * @return The novelId.
     */
    @java.lang.Override
    public int getNovelId() {
      return novelId_;
    }
    /**
     * <code>int32 NovelId = 1;</code>
     * @param value The novelId to set.
     */
    private void setNovelId(int value) {
      
      novelId_ = value;
    }
    /**
     * <code>int32 NovelId = 1;</code>
     */
    private void clearNovelId() {
      
      novelId_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string Name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string Name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int ZONE_FIELD_NUMBER = 3;
    private java.lang.String zone_;
    /**
     * <code>string Zone = 3;</code>
     * @return The zone.
     */
    @java.lang.Override
    public java.lang.String getZone() {
      return zone_;
    }
    /**
     * <code>string Zone = 3;</code>
     * @return The bytes for zone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(zone_);
    }
    /**
     * <code>string Zone = 3;</code>
     * @param value The zone to set.
     */
    private void setZone(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      zone_ = value;
    }
    /**
     * <code>string Zone = 3;</code>
     */
    private void clearZone() {
      
      zone_ = getDefaultInstance().getZone();
    }
    /**
     * <code>string Zone = 3;</code>
     * @param value The bytes for zone to set.
     */
    private void setZoneBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      zone_ = value.toStringUtf8();
      
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private java.lang.String status_;
    /**
     * <code>string Status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      return status_;
    }
    /**
     * <code>string Status = 4;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(status_);
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The status to set.
     */
    private void setStatus(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      status_ = value;
    }
    /**
     * <code>string Status = 4;</code>
     */
    private void clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
    }
    /**
     * <code>string Status = 4;</code>
     * @param value The bytes for status to set.
     */
    private void setStatusBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      status_ = value.toStringUtf8();
      
    }

    public static final int LASTUPDATEVOLUMENAME_FIELD_NUMBER = 5;
    private java.lang.String lastUpdateVolumeName_;
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @return The lastUpdateVolumeName.
     */
    @java.lang.Override
    public java.lang.String getLastUpdateVolumeName() {
      return lastUpdateVolumeName_;
    }
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @return The bytes for lastUpdateVolumeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastUpdateVolumeNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lastUpdateVolumeName_);
    }
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @param value The lastUpdateVolumeName to set.
     */
    private void setLastUpdateVolumeName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      lastUpdateVolumeName_ = value;
    }
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     */
    private void clearLastUpdateVolumeName() {
      
      lastUpdateVolumeName_ = getDefaultInstance().getLastUpdateVolumeName();
    }
    /**
     * <code>string LastUpdateVolumeName = 5;</code>
     * @param value The bytes for lastUpdateVolumeName to set.
     */
    private void setLastUpdateVolumeNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lastUpdateVolumeName_ = value.toStringUtf8();
      
    }

    public static final int LASTUPDATECHAPTERNAME_FIELD_NUMBER = 6;
    private java.lang.String lastUpdateChapterName_;
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @return The lastUpdateChapterName.
     */
    @java.lang.Override
    public java.lang.String getLastUpdateChapterName() {
      return lastUpdateChapterName_;
    }
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @return The bytes for lastUpdateChapterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastUpdateChapterNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lastUpdateChapterName_);
    }
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @param value The lastUpdateChapterName to set.
     */
    private void setLastUpdateChapterName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      lastUpdateChapterName_ = value;
    }
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     */
    private void clearLastUpdateChapterName() {
      
      lastUpdateChapterName_ = getDefaultInstance().getLastUpdateChapterName();
    }
    /**
     * <code>string LastUpdateChapterName = 6;</code>
     * @param value The bytes for lastUpdateChapterName to set.
     */
    private void setLastUpdateChapterNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lastUpdateChapterName_ = value.toStringUtf8();
      
    }

    public static final int LASTUPDATEVOLUMEID_FIELD_NUMBER = 7;
    private int lastUpdateVolumeId_;
    /**
     * <code>int32 LastUpdateVolumeId = 7;</code>
     * @return The lastUpdateVolumeId.
     */
    @java.lang.Override
    public int getLastUpdateVolumeId() {
      return lastUpdateVolumeId_;
    }
    /**
     * <code>int32 LastUpdateVolumeId = 7;</code>
     * @param value The lastUpdateVolumeId to set.
     */
    private void setLastUpdateVolumeId(int value) {
      
      lastUpdateVolumeId_ = value;
    }
    /**
     * <code>int32 LastUpdateVolumeId = 7;</code>
     */
    private void clearLastUpdateVolumeId() {
      
      lastUpdateVolumeId_ = 0;
    }

    public static final int LASTUPDATECHAPTERID_FIELD_NUMBER = 8;
    private int lastUpdateChapterId_;
    /**
     * <code>int32 LastUpdateChapterId = 8;</code>
     * @return The lastUpdateChapterId.
     */
    @java.lang.Override
    public int getLastUpdateChapterId() {
      return lastUpdateChapterId_;
    }
    /**
     * <code>int32 LastUpdateChapterId = 8;</code>
     * @param value The lastUpdateChapterId to set.
     */
    private void setLastUpdateChapterId(int value) {
      
      lastUpdateChapterId_ = value;
    }
    /**
     * <code>int32 LastUpdateChapterId = 8;</code>
     */
    private void clearLastUpdateChapterId() {
      
      lastUpdateChapterId_ = 0;
    }

    public static final int LASTUPDATETIME_FIELD_NUMBER = 9;
    private long lastUpdateTime_;
    /**
     * <code>int64 LastUpdateTime = 9;</code>
     * @return The lastUpdateTime.
     */
    @java.lang.Override
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    /**
     * <code>int64 LastUpdateTime = 9;</code>
     * @param value The lastUpdateTime to set.
     */
    private void setLastUpdateTime(long value) {
      
      lastUpdateTime_ = value;
    }
    /**
     * <code>int64 LastUpdateTime = 9;</code>
     */
    private void clearLastUpdateTime() {
      
      lastUpdateTime_ = 0L;
    }

    public static final int COVER_FIELD_NUMBER = 10;
    private java.lang.String cover_;
    /**
     * <code>string Cover = 10;</code>
     * @return The cover.
     */
    @java.lang.Override
    public java.lang.String getCover() {
      return cover_;
    }
    /**
     * <code>string Cover = 10;</code>
     * @return The bytes for cover.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoverBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cover_);
    }
    /**
     * <code>string Cover = 10;</code>
     * @param value The cover to set.
     */
    private void setCover(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      cover_ = value;
    }
    /**
     * <code>string Cover = 10;</code>
     */
    private void clearCover() {
      
      cover_ = getDefaultInstance().getCover();
    }
    /**
     * <code>string Cover = 10;</code>
     * @param value The bytes for cover to set.
     */
    private void setCoverBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cover_ = value.toStringUtf8();
      
    }

    public static final int HOTHITS_FIELD_NUMBER = 11;
    private int hotHits_;
    /**
     * <code>int32 HotHits = 11;</code>
     * @return The hotHits.
     */
    @java.lang.Override
    public int getHotHits() {
      return hotHits_;
    }
    /**
     * <code>int32 HotHits = 11;</code>
     * @param value The hotHits to set.
     */
    private void setHotHits(int value) {
      
      hotHits_ = value;
    }
    /**
     * <code>int32 HotHits = 11;</code>
     */
    private void clearHotHits() {
      
      hotHits_ = 0;
    }

    public static final int INTRODUCTION_FIELD_NUMBER = 12;
    private java.lang.String introduction_;
    /**
     * <code>string Introduction = 12;</code>
     * @return The introduction.
     */
    @java.lang.Override
    public java.lang.String getIntroduction() {
      return introduction_;
    }
    /**
     * <code>string Introduction = 12;</code>
     * @return The bytes for introduction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIntroductionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(introduction_);
    }
    /**
     * <code>string Introduction = 12;</code>
     * @param value The introduction to set.
     */
    private void setIntroduction(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      introduction_ = value;
    }
    /**
     * <code>string Introduction = 12;</code>
     */
    private void clearIntroduction() {
      
      introduction_ = getDefaultInstance().getIntroduction();
    }
    /**
     * <code>string Introduction = 12;</code>
     * @param value The bytes for introduction to set.
     */
    private void setIntroductionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      introduction_ = value.toStringUtf8();
      
    }

    public static final int TYPES_FIELD_NUMBER = 13;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> types_;
    /**
     * <code>repeated string Types = 13;</code>
     * @return A list containing the types.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getTypesList() {
      return types_;
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @return The count of types.
     */
    @java.lang.Override
    public int getTypesCount() {
      return types_.size();
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    @java.lang.Override
    public java.lang.String getTypes(int index) {
      return types_.get(index);
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param index The index of the value to return.
     * @return The bytes of the types at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypesBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          types_.get(index));
    }
    private void ensureTypesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          types_;  if (!tmp.isModifiable()) {
        types_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param index The index to set the value at.
     * @param value The types to set.
     */
    private void setTypes(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureTypesIsMutable();
      types_.set(index, value);
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param value The types to add.
     */
    private void addTypes(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureTypesIsMutable();
      types_.add(value);
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param values The types to add.
     */
    private void addAllTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, types_);
    }
    /**
     * <code>repeated string Types = 13;</code>
     */
    private void clearTypes() {
      types_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string Types = 13;</code>
     * @param value The bytes of the types to add.
     */
    private void addTypesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureTypesIsMutable();
      types_.add(value.toStringUtf8());
    }

    public static final int AUTHORS_FIELD_NUMBER = 14;
    private java.lang.String authors_;
    /**
     * <code>string Authors = 14;</code>
     * @return The authors.
     */
    @java.lang.Override
    public java.lang.String getAuthors() {
      return authors_;
    }
    /**
     * <code>string Authors = 14;</code>
     * @return The bytes for authors.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(authors_);
    }
    /**
     * <code>string Authors = 14;</code>
     * @param value The authors to set.
     */
    private void setAuthors(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      authors_ = value;
    }
    /**
     * <code>string Authors = 14;</code>
     */
    private void clearAuthors() {
      
      authors_ = getDefaultInstance().getAuthors();
    }
    /**
     * <code>string Authors = 14;</code>
     * @param value The bytes for authors to set.
     */
    private void setAuthorsBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      authors_ = value.toStringUtf8();
      
    }

    public static final int FIRSTLETTER_FIELD_NUMBER = 15;
    private java.lang.String firstLetter_;
    /**
     * <code>string FirstLetter = 15;</code>
     * @return The firstLetter.
     */
    @java.lang.Override
    public java.lang.String getFirstLetter() {
      return firstLetter_;
    }
    /**
     * <code>string FirstLetter = 15;</code>
     * @return The bytes for firstLetter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstLetterBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(firstLetter_);
    }
    /**
     * <code>string FirstLetter = 15;</code>
     * @param value The firstLetter to set.
     */
    private void setFirstLetter(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      firstLetter_ = value;
    }
    /**
     * <code>string FirstLetter = 15;</code>
     */
    private void clearFirstLetter() {
      
      firstLetter_ = getDefaultInstance().getFirstLetter();
    }
    /**
     * <code>string FirstLetter = 15;</code>
     * @param value The bytes for firstLetter to set.
     */
    private void setFirstLetterBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      firstLetter_ = value.toStringUtf8();
      
    }

    public static final int SUBSCRIBENUM_FIELD_NUMBER = 16;
    private int subscribeNum_;
    /**
     * <code>int32 SubscribeNum = 16;</code>
     * @return The subscribeNum.
     */
    @java.lang.Override
    public int getSubscribeNum() {
      return subscribeNum_;
    }
    /**
     * <code>int32 SubscribeNum = 16;</code>
     * @param value The subscribeNum to set.
     */
    private void setSubscribeNum(int value) {
      
      subscribeNum_ = value;
    }
    /**
     * <code>int32 SubscribeNum = 16;</code>
     */
    private void clearSubscribeNum() {
      
      subscribeNum_ = 0;
    }

    public static final int REDISUPDATETIME_FIELD_NUMBER = 17;
    private long redisUpdateTime_;
    /**
     * <code>int64 RedisUpdateTime = 17;</code>
     * @return The redisUpdateTime.
     */
    @java.lang.Override
    public long getRedisUpdateTime() {
      return redisUpdateTime_;
    }
    /**
     * <code>int64 RedisUpdateTime = 17;</code>
     * @param value The redisUpdateTime to set.
     */
    private void setRedisUpdateTime(long value) {
      
      redisUpdateTime_ = value;
    }
    /**
     * <code>int64 RedisUpdateTime = 17;</code>
     */
    private void clearRedisUpdateTime() {
      
      redisUpdateTime_ = 0L;
    }

    public static final int VOLUME_FIELD_NUMBER = 18;
    private com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> volume_;
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> getVolumeList() {
      return volume_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    public java.util.List<? extends com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponseOrBuilder> 
        getVolumeOrBuilderList() {
      return volume_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    @java.lang.Override
    public int getVolumeCount() {
      return volume_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse getVolume(int index) {
      return volume_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    public com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponseOrBuilder getVolumeOrBuilder(
        int index) {
      return volume_.get(index);
    }
    private void ensureVolumeIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> tmp = volume_;
      if (!tmp.isModifiable()) {
        volume_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void setVolume(
        int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
      value.getClass();
  ensureVolumeIsMutable();
      volume_.set(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void addVolume(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
      value.getClass();
  ensureVolumeIsMutable();
      volume_.add(value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void addVolume(
        int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
      value.getClass();
  ensureVolumeIsMutable();
      volume_.add(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void addAllVolume(
        java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> values) {
      ensureVolumeIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, volume_);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void clearVolume() {
      volume_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
     */
    private void removeVolume(int index) {
      ensureVolumeIsMutable();
      volume_.remove(index);
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelDetailInfoResponse)
        com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 NovelId = 1;</code>
       * @return The novelId.
       */
      @java.lang.Override
      public int getNovelId() {
        return instance.getNovelId();
      }
      /**
       * <code>int32 NovelId = 1;</code>
       * @param value The novelId to set.
       * @return This builder for chaining.
       */
      public Builder setNovelId(int value) {
        copyOnWrite();
        instance.setNovelId(value);
        return this;
      }
      /**
       * <code>int32 NovelId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNovelId() {
        copyOnWrite();
        instance.clearNovelId();
        return this;
      }

      /**
       * <code>string Name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string Name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string Name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string Name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string Name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string Zone = 3;</code>
       * @return The zone.
       */
      @java.lang.Override
      public java.lang.String getZone() {
        return instance.getZone();
      }
      /**
       * <code>string Zone = 3;</code>
       * @return The bytes for zone.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getZoneBytes() {
        return instance.getZoneBytes();
      }
      /**
       * <code>string Zone = 3;</code>
       * @param value The zone to set.
       * @return This builder for chaining.
       */
      public Builder setZone(
          java.lang.String value) {
        copyOnWrite();
        instance.setZone(value);
        return this;
      }
      /**
       * <code>string Zone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZone() {
        copyOnWrite();
        instance.clearZone();
        return this;
      }
      /**
       * <code>string Zone = 3;</code>
       * @param value The bytes for zone to set.
       * @return This builder for chaining.
       */
      public Builder setZoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setZoneBytes(value);
        return this;
      }

      /**
       * <code>string Status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public java.lang.String getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>string Status = 4;</code>
       * @return The bytes for status.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStatusBytes() {
        return instance.getStatusBytes();
      }
      /**
       * <code>string Status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>string Status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }
      /**
       * <code>string Status = 4;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStatusBytes(value);
        return this;
      }

      /**
       * <code>string LastUpdateVolumeName = 5;</code>
       * @return The lastUpdateVolumeName.
       */
      @java.lang.Override
      public java.lang.String getLastUpdateVolumeName() {
        return instance.getLastUpdateVolumeName();
      }
      /**
       * <code>string LastUpdateVolumeName = 5;</code>
       * @return The bytes for lastUpdateVolumeName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLastUpdateVolumeNameBytes() {
        return instance.getLastUpdateVolumeNameBytes();
      }
      /**
       * <code>string LastUpdateVolumeName = 5;</code>
       * @param value The lastUpdateVolumeName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateVolumeName(
          java.lang.String value) {
        copyOnWrite();
        instance.setLastUpdateVolumeName(value);
        return this;
      }
      /**
       * <code>string LastUpdateVolumeName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateVolumeName() {
        copyOnWrite();
        instance.clearLastUpdateVolumeName();
        return this;
      }
      /**
       * <code>string LastUpdateVolumeName = 5;</code>
       * @param value The bytes for lastUpdateVolumeName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateVolumeNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLastUpdateVolumeNameBytes(value);
        return this;
      }

      /**
       * <code>string LastUpdateChapterName = 6;</code>
       * @return The lastUpdateChapterName.
       */
      @java.lang.Override
      public java.lang.String getLastUpdateChapterName() {
        return instance.getLastUpdateChapterName();
      }
      /**
       * <code>string LastUpdateChapterName = 6;</code>
       * @return The bytes for lastUpdateChapterName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLastUpdateChapterNameBytes() {
        return instance.getLastUpdateChapterNameBytes();
      }
      /**
       * <code>string LastUpdateChapterName = 6;</code>
       * @param value The lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterName(
          java.lang.String value) {
        copyOnWrite();
        instance.setLastUpdateChapterName(value);
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateChapterName() {
        copyOnWrite();
        instance.clearLastUpdateChapterName();
        return this;
      }
      /**
       * <code>string LastUpdateChapterName = 6;</code>
       * @param value The bytes for lastUpdateChapterName to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLastUpdateChapterNameBytes(value);
        return this;
      }

      /**
       * <code>int32 LastUpdateVolumeId = 7;</code>
       * @return The lastUpdateVolumeId.
       */
      @java.lang.Override
      public int getLastUpdateVolumeId() {
        return instance.getLastUpdateVolumeId();
      }
      /**
       * <code>int32 LastUpdateVolumeId = 7;</code>
       * @param value The lastUpdateVolumeId to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateVolumeId(int value) {
        copyOnWrite();
        instance.setLastUpdateVolumeId(value);
        return this;
      }
      /**
       * <code>int32 LastUpdateVolumeId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateVolumeId() {
        copyOnWrite();
        instance.clearLastUpdateVolumeId();
        return this;
      }

      /**
       * <code>int32 LastUpdateChapterId = 8;</code>
       * @return The lastUpdateChapterId.
       */
      @java.lang.Override
      public int getLastUpdateChapterId() {
        return instance.getLastUpdateChapterId();
      }
      /**
       * <code>int32 LastUpdateChapterId = 8;</code>
       * @param value The lastUpdateChapterId to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateChapterId(int value) {
        copyOnWrite();
        instance.setLastUpdateChapterId(value);
        return this;
      }
      /**
       * <code>int32 LastUpdateChapterId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateChapterId() {
        copyOnWrite();
        instance.clearLastUpdateChapterId();
        return this;
      }

      /**
       * <code>int64 LastUpdateTime = 9;</code>
       * @return The lastUpdateTime.
       */
      @java.lang.Override
      public long getLastUpdateTime() {
        return instance.getLastUpdateTime();
      }
      /**
       * <code>int64 LastUpdateTime = 9;</code>
       * @param value The lastUpdateTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateTime(long value) {
        copyOnWrite();
        instance.setLastUpdateTime(value);
        return this;
      }
      /**
       * <code>int64 LastUpdateTime = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateTime() {
        copyOnWrite();
        instance.clearLastUpdateTime();
        return this;
      }

      /**
       * <code>string Cover = 10;</code>
       * @return The cover.
       */
      @java.lang.Override
      public java.lang.String getCover() {
        return instance.getCover();
      }
      /**
       * <code>string Cover = 10;</code>
       * @return The bytes for cover.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCoverBytes() {
        return instance.getCoverBytes();
      }
      /**
       * <code>string Cover = 10;</code>
       * @param value The cover to set.
       * @return This builder for chaining.
       */
      public Builder setCover(
          java.lang.String value) {
        copyOnWrite();
        instance.setCover(value);
        return this;
      }
      /**
       * <code>string Cover = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCover() {
        copyOnWrite();
        instance.clearCover();
        return this;
      }
      /**
       * <code>string Cover = 10;</code>
       * @param value The bytes for cover to set.
       * @return This builder for chaining.
       */
      public Builder setCoverBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCoverBytes(value);
        return this;
      }

      /**
       * <code>int32 HotHits = 11;</code>
       * @return The hotHits.
       */
      @java.lang.Override
      public int getHotHits() {
        return instance.getHotHits();
      }
      /**
       * <code>int32 HotHits = 11;</code>
       * @param value The hotHits to set.
       * @return This builder for chaining.
       */
      public Builder setHotHits(int value) {
        copyOnWrite();
        instance.setHotHits(value);
        return this;
      }
      /**
       * <code>int32 HotHits = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotHits() {
        copyOnWrite();
        instance.clearHotHits();
        return this;
      }

      /**
       * <code>string Introduction = 12;</code>
       * @return The introduction.
       */
      @java.lang.Override
      public java.lang.String getIntroduction() {
        return instance.getIntroduction();
      }
      /**
       * <code>string Introduction = 12;</code>
       * @return The bytes for introduction.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIntroductionBytes() {
        return instance.getIntroductionBytes();
      }
      /**
       * <code>string Introduction = 12;</code>
       * @param value The introduction to set.
       * @return This builder for chaining.
       */
      public Builder setIntroduction(
          java.lang.String value) {
        copyOnWrite();
        instance.setIntroduction(value);
        return this;
      }
      /**
       * <code>string Introduction = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntroduction() {
        copyOnWrite();
        instance.clearIntroduction();
        return this;
      }
      /**
       * <code>string Introduction = 12;</code>
       * @param value The bytes for introduction to set.
       * @return This builder for chaining.
       */
      public Builder setIntroductionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIntroductionBytes(value);
        return this;
      }

      /**
       * <code>repeated string Types = 13;</code>
       * @return A list containing the types.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getTypesList() {
        return java.util.Collections.unmodifiableList(
            instance.getTypesList());
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @return The count of types.
       */
      @java.lang.Override
      public int getTypesCount() {
        return instance.getTypesCount();
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param index The index of the element to return.
       * @return The types at the given index.
       */
      @java.lang.Override
      public java.lang.String getTypes(int index) {
        return instance.getTypes(index);
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param index The index of the value to return.
       * @return The bytes of the types at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypesBytes(int index) {
        return instance.getTypesBytes(index);
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param index The index to set the value at.
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setTypes(index, value);
        return this;
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param value The types to add.
       * @return This builder for chaining.
       */
      public Builder addTypes(
          java.lang.String value) {
        copyOnWrite();
        instance.addTypes(value);
        return this;
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param values The types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypes(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllTypes(values);
        return this;
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        copyOnWrite();
        instance.clearTypes();
        return this;
      }
      /**
       * <code>repeated string Types = 13;</code>
       * @param value The bytes of the types to add.
       * @return This builder for chaining.
       */
      public Builder addTypesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addTypesBytes(value);
        return this;
      }

      /**
       * <code>string Authors = 14;</code>
       * @return The authors.
       */
      @java.lang.Override
      public java.lang.String getAuthors() {
        return instance.getAuthors();
      }
      /**
       * <code>string Authors = 14;</code>
       * @return The bytes for authors.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAuthorsBytes() {
        return instance.getAuthorsBytes();
      }
      /**
       * <code>string Authors = 14;</code>
       * @param value The authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthors(
          java.lang.String value) {
        copyOnWrite();
        instance.setAuthors(value);
        return this;
      }
      /**
       * <code>string Authors = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthors() {
        copyOnWrite();
        instance.clearAuthors();
        return this;
      }
      /**
       * <code>string Authors = 14;</code>
       * @param value The bytes for authors to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAuthorsBytes(value);
        return this;
      }

      /**
       * <code>string FirstLetter = 15;</code>
       * @return The firstLetter.
       */
      @java.lang.Override
      public java.lang.String getFirstLetter() {
        return instance.getFirstLetter();
      }
      /**
       * <code>string FirstLetter = 15;</code>
       * @return The bytes for firstLetter.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFirstLetterBytes() {
        return instance.getFirstLetterBytes();
      }
      /**
       * <code>string FirstLetter = 15;</code>
       * @param value The firstLetter to set.
       * @return This builder for chaining.
       */
      public Builder setFirstLetter(
          java.lang.String value) {
        copyOnWrite();
        instance.setFirstLetter(value);
        return this;
      }
      /**
       * <code>string FirstLetter = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstLetter() {
        copyOnWrite();
        instance.clearFirstLetter();
        return this;
      }
      /**
       * <code>string FirstLetter = 15;</code>
       * @param value The bytes for firstLetter to set.
       * @return This builder for chaining.
       */
      public Builder setFirstLetterBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFirstLetterBytes(value);
        return this;
      }

      /**
       * <code>int32 SubscribeNum = 16;</code>
       * @return The subscribeNum.
       */
      @java.lang.Override
      public int getSubscribeNum() {
        return instance.getSubscribeNum();
      }
      /**
       * <code>int32 SubscribeNum = 16;</code>
       * @param value The subscribeNum to set.
       * @return This builder for chaining.
       */
      public Builder setSubscribeNum(int value) {
        copyOnWrite();
        instance.setSubscribeNum(value);
        return this;
      }
      /**
       * <code>int32 SubscribeNum = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscribeNum() {
        copyOnWrite();
        instance.clearSubscribeNum();
        return this;
      }

      /**
       * <code>int64 RedisUpdateTime = 17;</code>
       * @return The redisUpdateTime.
       */
      @java.lang.Override
      public long getRedisUpdateTime() {
        return instance.getRedisUpdateTime();
      }
      /**
       * <code>int64 RedisUpdateTime = 17;</code>
       * @param value The redisUpdateTime to set.
       * @return This builder for chaining.
       */
      public Builder setRedisUpdateTime(long value) {
        copyOnWrite();
        instance.setRedisUpdateTime(value);
        return this;
      }
      /**
       * <code>int64 RedisUpdateTime = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearRedisUpdateTime() {
        copyOnWrite();
        instance.clearRedisUpdateTime();
        return this;
      }

      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> getVolumeList() {
        return java.util.Collections.unmodifiableList(
            instance.getVolumeList());
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      @java.lang.Override
      public int getVolumeCount() {
        return instance.getVolumeCount();
      }/**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse getVolume(int index) {
        return instance.getVolume(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder setVolume(
          int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
        copyOnWrite();
        instance.setVolume(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder setVolume(
          int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setVolume(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder addVolume(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
        copyOnWrite();
        instance.addVolume(value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder addVolume(
          int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse value) {
        copyOnWrite();
        instance.addVolume(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder addVolume(
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addVolume(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder addVolume(
          int index, com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addVolume(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder addAllVolume(
          java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> values) {
        copyOnWrite();
        instance.addAllVolume(values);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder clearVolume() {
        copyOnWrite();
        instance.clearVolume();
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse Volume = 18;</code>
       */
      public Builder removeVolume(int index) {
        copyOnWrite();
        instance.removeVolume(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelDetailInfoResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "novelId_",
              "name_",
              "zone_",
              "status_",
              "lastUpdateVolumeName_",
              "lastUpdateChapterName_",
              "lastUpdateVolumeId_",
              "lastUpdateChapterId_",
              "lastUpdateTime_",
              "cover_",
              "hotHits_",
              "introduction_",
              "types_",
              "authors_",
              "firstLetter_",
              "subscribeNum_",
              "redisUpdateTime_",
              "volume_",
              com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.class,
            };
            java.lang.String info =
                "\u0000\u0012\u0000\u0000\u0001\u0012\u0012\u0000\u0002\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0004\b\u0004\t\u0002\n\u0208" +
                "\u000b\u0004\f\u0208\r\u021a\u000e\u0208\u000f\u0208\u0010\u0004\u0011\u0002\u0012" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelDetailInfoResponse)
    private static final com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse DEFAULT_INSTANCE;
    static {
      NovelDetailInfoResponse defaultInstance = new NovelDetailInfoResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelDetailInfoResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelDetailInfoResponse> PARSER;

    public static com.google.protobuf.Parser<NovelDetailInfoResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NovelDetailInfoVolumeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 VolumeId = 1;</code>
     * @return The volumeId.
     */
    int getVolumeId();

    /**
     * <code>int32 LnovelId = 2;</code>
     * @return The lnovelId.
     */
    int getLnovelId();

    /**
     * <code>string VolumeName = 3;</code>
     * @return The volumeName.
     */
    java.lang.String getVolumeName();
    /**
     * <code>string VolumeName = 3;</code>
     * @return The bytes for volumeName.
     */
    com.google.protobuf.ByteString
        getVolumeNameBytes();

    /**
     * <code>int32 VolumeOrder = 4;</code>
     * @return The volumeOrder.
     */
    int getVolumeOrder();

    /**
     * <code>int64 Addtime = 5;</code>
     * @return The addtime.
     */
    long getAddtime();

    /**
     * <code>int32 SumChapters = 6;</code>
     * @return The sumChapters.
     */
    int getSumChapters();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse}
   */
  public  static final class NovelDetailInfoVolumeResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelDetailInfoVolumeResponse, NovelDetailInfoVolumeResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse)
      NovelDetailInfoVolumeResponseOrBuilder {
    private NovelDetailInfoVolumeResponse() {
      volumeName_ = "";
    }
    public static final int VOLUMEID_FIELD_NUMBER = 1;
    private int volumeId_;
    /**
     * <code>int32 VolumeId = 1;</code>
     * @return The volumeId.
     */
    @java.lang.Override
    public int getVolumeId() {
      return volumeId_;
    }
    /**
     * <code>int32 VolumeId = 1;</code>
     * @param value The volumeId to set.
     */
    private void setVolumeId(int value) {
      
      volumeId_ = value;
    }
    /**
     * <code>int32 VolumeId = 1;</code>
     */
    private void clearVolumeId() {
      
      volumeId_ = 0;
    }

    public static final int LNOVELID_FIELD_NUMBER = 2;
    private int lnovelId_;
    /**
     * <code>int32 LnovelId = 2;</code>
     * @return The lnovelId.
     */
    @java.lang.Override
    public int getLnovelId() {
      return lnovelId_;
    }
    /**
     * <code>int32 LnovelId = 2;</code>
     * @param value The lnovelId to set.
     */
    private void setLnovelId(int value) {
      
      lnovelId_ = value;
    }
    /**
     * <code>int32 LnovelId = 2;</code>
     */
    private void clearLnovelId() {
      
      lnovelId_ = 0;
    }

    public static final int VOLUMENAME_FIELD_NUMBER = 3;
    private java.lang.String volumeName_;
    /**
     * <code>string VolumeName = 3;</code>
     * @return The volumeName.
     */
    @java.lang.Override
    public java.lang.String getVolumeName() {
      return volumeName_;
    }
    /**
     * <code>string VolumeName = 3;</code>
     * @return The bytes for volumeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVolumeNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(volumeName_);
    }
    /**
     * <code>string VolumeName = 3;</code>
     * @param value The volumeName to set.
     */
    private void setVolumeName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      volumeName_ = value;
    }
    /**
     * <code>string VolumeName = 3;</code>
     */
    private void clearVolumeName() {
      
      volumeName_ = getDefaultInstance().getVolumeName();
    }
    /**
     * <code>string VolumeName = 3;</code>
     * @param value The bytes for volumeName to set.
     */
    private void setVolumeNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      volumeName_ = value.toStringUtf8();
      
    }

    public static final int VOLUMEORDER_FIELD_NUMBER = 4;
    private int volumeOrder_;
    /**
     * <code>int32 VolumeOrder = 4;</code>
     * @return The volumeOrder.
     */
    @java.lang.Override
    public int getVolumeOrder() {
      return volumeOrder_;
    }
    /**
     * <code>int32 VolumeOrder = 4;</code>
     * @param value The volumeOrder to set.
     */
    private void setVolumeOrder(int value) {
      
      volumeOrder_ = value;
    }
    /**
     * <code>int32 VolumeOrder = 4;</code>
     */
    private void clearVolumeOrder() {
      
      volumeOrder_ = 0;
    }

    public static final int ADDTIME_FIELD_NUMBER = 5;
    private long addtime_;
    /**
     * <code>int64 Addtime = 5;</code>
     * @return The addtime.
     */
    @java.lang.Override
    public long getAddtime() {
      return addtime_;
    }
    /**
     * <code>int64 Addtime = 5;</code>
     * @param value The addtime to set.
     */
    private void setAddtime(long value) {
      
      addtime_ = value;
    }
    /**
     * <code>int64 Addtime = 5;</code>
     */
    private void clearAddtime() {
      
      addtime_ = 0L;
    }

    public static final int SUMCHAPTERS_FIELD_NUMBER = 6;
    private int sumChapters_;
    /**
     * <code>int32 SumChapters = 6;</code>
     * @return The sumChapters.
     */
    @java.lang.Override
    public int getSumChapters() {
      return sumChapters_;
    }
    /**
     * <code>int32 SumChapters = 6;</code>
     * @param value The sumChapters to set.
     */
    private void setSumChapters(int value) {
      
      sumChapters_ = value;
    }
    /**
     * <code>int32 SumChapters = 6;</code>
     */
    private void clearSumChapters() {
      
      sumChapters_ = 0;
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse)
        com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 VolumeId = 1;</code>
       * @return The volumeId.
       */
      @java.lang.Override
      public int getVolumeId() {
        return instance.getVolumeId();
      }
      /**
       * <code>int32 VolumeId = 1;</code>
       * @param value The volumeId to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeId(int value) {
        copyOnWrite();
        instance.setVolumeId(value);
        return this;
      }
      /**
       * <code>int32 VolumeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeId() {
        copyOnWrite();
        instance.clearVolumeId();
        return this;
      }

      /**
       * <code>int32 LnovelId = 2;</code>
       * @return The lnovelId.
       */
      @java.lang.Override
      public int getLnovelId() {
        return instance.getLnovelId();
      }
      /**
       * <code>int32 LnovelId = 2;</code>
       * @param value The lnovelId to set.
       * @return This builder for chaining.
       */
      public Builder setLnovelId(int value) {
        copyOnWrite();
        instance.setLnovelId(value);
        return this;
      }
      /**
       * <code>int32 LnovelId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLnovelId() {
        copyOnWrite();
        instance.clearLnovelId();
        return this;
      }

      /**
       * <code>string VolumeName = 3;</code>
       * @return The volumeName.
       */
      @java.lang.Override
      public java.lang.String getVolumeName() {
        return instance.getVolumeName();
      }
      /**
       * <code>string VolumeName = 3;</code>
       * @return The bytes for volumeName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVolumeNameBytes() {
        return instance.getVolumeNameBytes();
      }
      /**
       * <code>string VolumeName = 3;</code>
       * @param value The volumeName to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeName(
          java.lang.String value) {
        copyOnWrite();
        instance.setVolumeName(value);
        return this;
      }
      /**
       * <code>string VolumeName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeName() {
        copyOnWrite();
        instance.clearVolumeName();
        return this;
      }
      /**
       * <code>string VolumeName = 3;</code>
       * @param value The bytes for volumeName to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVolumeNameBytes(value);
        return this;
      }

      /**
       * <code>int32 VolumeOrder = 4;</code>
       * @return The volumeOrder.
       */
      @java.lang.Override
      public int getVolumeOrder() {
        return instance.getVolumeOrder();
      }
      /**
       * <code>int32 VolumeOrder = 4;</code>
       * @param value The volumeOrder to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeOrder(int value) {
        copyOnWrite();
        instance.setVolumeOrder(value);
        return this;
      }
      /**
       * <code>int32 VolumeOrder = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeOrder() {
        copyOnWrite();
        instance.clearVolumeOrder();
        return this;
      }

      /**
       * <code>int64 Addtime = 5;</code>
       * @return The addtime.
       */
      @java.lang.Override
      public long getAddtime() {
        return instance.getAddtime();
      }
      /**
       * <code>int64 Addtime = 5;</code>
       * @param value The addtime to set.
       * @return This builder for chaining.
       */
      public Builder setAddtime(long value) {
        copyOnWrite();
        instance.setAddtime(value);
        return this;
      }
      /**
       * <code>int64 Addtime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddtime() {
        copyOnWrite();
        instance.clearAddtime();
        return this;
      }

      /**
       * <code>int32 SumChapters = 6;</code>
       * @return The sumChapters.
       */
      @java.lang.Override
      public int getSumChapters() {
        return instance.getSumChapters();
      }
      /**
       * <code>int32 SumChapters = 6;</code>
       * @param value The sumChapters to set.
       * @return This builder for chaining.
       */
      public Builder setSumChapters(int value) {
        copyOnWrite();
        instance.setSumChapters(value);
        return this;
      }
      /**
       * <code>int32 SumChapters = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSumChapters() {
        copyOnWrite();
        instance.clearSumChapters();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "volumeId_",
              "lnovelId_",
              "volumeName_",
              "volumeOrder_",
              "addtime_",
              "sumChapters_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0208\u0004\u0004\u0005\u0002\u0006\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelDetailInfoVolumeResponse)
    private static final com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse DEFAULT_INSTANCE;
    static {
      NovelDetailInfoVolumeResponse defaultInstance = new NovelDetailInfoVolumeResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelDetailInfoVolumeResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelDetailRes.NovelDetailInfoVolumeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelDetailInfoVolumeResponse> PARSER;

    public static com.google.protobuf.Parser<NovelDetailInfoVolumeResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
