// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NovelChapterResponse.proto

package com.example.dmzj_api.pojo;

public final class NovelChapterRes {
  private NovelChapterRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NovelChapterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelChapterResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    int getErrno();

    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    java.lang.String getErrmsg();
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> 
        getDataList();
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse getData(int index);
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterResponse}
   */
  public  static final class NovelChapterResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelChapterResponse, NovelChapterResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelChapterResponse)
      NovelChapterResponseOrBuilder {
    private NovelChapterResponse() {
      errmsg_ = "";
      data_ = emptyProtobufList();
    }
    public static final int ERRNO_FIELD_NUMBER = 1;
    private int errno_;
    /**
     * <code>int32 Errno = 1;</code>
     * @return The errno.
     */
    @java.lang.Override
    public int getErrno() {
      return errno_;
    }
    /**
     * <code>int32 Errno = 1;</code>
     * @param value The errno to set.
     */
    private void setErrno(int value) {
      
      errno_ = value;
    }
    /**
     * <code>int32 Errno = 1;</code>
     */
    private void clearErrno() {
      
      errno_ = 0;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.String errmsg_;
    /**
     * <code>string Errmsg = 2;</code>
     * @return The errmsg.
     */
    @java.lang.Override
    public java.lang.String getErrmsg() {
      return errmsg_;
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @return The bytes for errmsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errmsg_);
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The errmsg to set.
     */
    private void setErrmsg(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      errmsg_ = value;
    }
    /**
     * <code>string Errmsg = 2;</code>
     */
    private void clearErrmsg() {
      
      errmsg_ = getDefaultInstance().getErrmsg();
    }
    /**
     * <code>string Errmsg = 2;</code>
     * @param value The bytes for errmsg to set.
     */
    private void setErrmsgBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errmsg_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> data_;
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    public java.util.List<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponseOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponseOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> tmp = data_;
      if (!tmp.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void setData(
        int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void addData(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void addData(
        int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
      value.getClass();
  ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void addAllData(
        java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelChapterResponse)
        com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 Errno = 1;</code>
       * @return The errno.
       */
      @java.lang.Override
      public int getErrno() {
        return instance.getErrno();
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @param value The errno to set.
       * @return This builder for chaining.
       */
      public Builder setErrno(int value) {
        copyOnWrite();
        instance.setErrno(value);
        return this;
      }
      /**
       * <code>int32 Errno = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrno() {
        copyOnWrite();
        instance.clearErrno();
        return this;
      }

      /**
       * <code>string Errmsg = 2;</code>
       * @return The errmsg.
       */
      @java.lang.Override
      public java.lang.String getErrmsg() {
        return instance.getErrmsg();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return The bytes for errmsg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        return instance.getErrmsgBytes();
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrmsg(value);
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrmsg() {
        copyOnWrite();
        instance.clearErrmsg();
        return this;
      }
      /**
       * <code>string Errmsg = 2;</code>
       * @param value The bytes for errmsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrmsgBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      @java.lang.Override
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse getData(int index) {
        return instance.getData(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder setData(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder addData(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder addData(
          com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder addData(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterVolumeResponse Data = 3;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelChapterResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "errno_",
              "errmsg_",
              "data_",
              com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelChapterResponse)
    private static final com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse DEFAULT_INSTANCE;
    static {
      NovelChapterResponse defaultInstance = new NovelChapterResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelChapterResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelChapterResponse> PARSER;

    public static com.google.protobuf.Parser<NovelChapterResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NovelChapterVolumeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelChapterVolumeResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 VolumeId = 1;</code>
     * @return The volumeId.
     */
    int getVolumeId();

    /**
     * <code>string VolumeName = 2;</code>
     * @return The volumeName.
     */
    java.lang.String getVolumeName();
    /**
     * <code>string VolumeName = 2;</code>
     * @return The bytes for volumeName.
     */
    com.google.protobuf.ByteString
        getVolumeNameBytes();

    /**
     * <code>int32 VolumeOrder = 3;</code>
     * @return The volumeOrder.
     */
    int getVolumeOrder();

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> 
        getChaptersList();
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse getChapters(int index);
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    int getChaptersCount();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterVolumeResponse}
   */
  public  static final class NovelChapterVolumeResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelChapterVolumeResponse, NovelChapterVolumeResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelChapterVolumeResponse)
      NovelChapterVolumeResponseOrBuilder {
    private NovelChapterVolumeResponse() {
      volumeName_ = "";
      chapters_ = emptyProtobufList();
    }
    public static final int VOLUMEID_FIELD_NUMBER = 1;
    private int volumeId_;
    /**
     * <code>int32 VolumeId = 1;</code>
     * @return The volumeId.
     */
    @java.lang.Override
    public int getVolumeId() {
      return volumeId_;
    }
    /**
     * <code>int32 VolumeId = 1;</code>
     * @param value The volumeId to set.
     */
    private void setVolumeId(int value) {
      
      volumeId_ = value;
    }
    /**
     * <code>int32 VolumeId = 1;</code>
     */
    private void clearVolumeId() {
      
      volumeId_ = 0;
    }

    public static final int VOLUMENAME_FIELD_NUMBER = 2;
    private java.lang.String volumeName_;
    /**
     * <code>string VolumeName = 2;</code>
     * @return The volumeName.
     */
    @java.lang.Override
    public java.lang.String getVolumeName() {
      return volumeName_;
    }
    /**
     * <code>string VolumeName = 2;</code>
     * @return The bytes for volumeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVolumeNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(volumeName_);
    }
    /**
     * <code>string VolumeName = 2;</code>
     * @param value The volumeName to set.
     */
    private void setVolumeName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      volumeName_ = value;
    }
    /**
     * <code>string VolumeName = 2;</code>
     */
    private void clearVolumeName() {
      
      volumeName_ = getDefaultInstance().getVolumeName();
    }
    /**
     * <code>string VolumeName = 2;</code>
     * @param value The bytes for volumeName to set.
     */
    private void setVolumeNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      volumeName_ = value.toStringUtf8();
      
    }

    public static final int VOLUMEORDER_FIELD_NUMBER = 3;
    private int volumeOrder_;
    /**
     * <code>int32 VolumeOrder = 3;</code>
     * @return The volumeOrder.
     */
    @java.lang.Override
    public int getVolumeOrder() {
      return volumeOrder_;
    }
    /**
     * <code>int32 VolumeOrder = 3;</code>
     * @param value The volumeOrder to set.
     */
    private void setVolumeOrder(int value) {
      
      volumeOrder_ = value;
    }
    /**
     * <code>int32 VolumeOrder = 3;</code>
     */
    private void clearVolumeOrder() {
      
      volumeOrder_ = 0;
    }

    public static final int CHAPTERS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> chapters_;
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> getChaptersList() {
      return chapters_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    public java.util.List<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponseOrBuilder> 
        getChaptersOrBuilderList() {
      return chapters_;
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    @java.lang.Override
    public int getChaptersCount() {
      return chapters_.size();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    @java.lang.Override
    public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse getChapters(int index) {
      return chapters_.get(index);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponseOrBuilder getChaptersOrBuilder(
        int index) {
      return chapters_.get(index);
    }
    private void ensureChaptersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> tmp = chapters_;
      if (!tmp.isModifiable()) {
        chapters_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void setChapters(
        int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
      value.getClass();
  ensureChaptersIsMutable();
      chapters_.set(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void addChapters(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
      value.getClass();
  ensureChaptersIsMutable();
      chapters_.add(value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void addChapters(
        int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
      value.getClass();
  ensureChaptersIsMutable();
      chapters_.add(index, value);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void addAllChapters(
        java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> values) {
      ensureChaptersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, chapters_);
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void clearChapters() {
      chapters_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
     */
    private void removeChapters(int index) {
      ensureChaptersIsMutable();
      chapters_.remove(index);
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterVolumeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelChapterVolumeResponse)
        com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 VolumeId = 1;</code>
       * @return The volumeId.
       */
      @java.lang.Override
      public int getVolumeId() {
        return instance.getVolumeId();
      }
      /**
       * <code>int32 VolumeId = 1;</code>
       * @param value The volumeId to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeId(int value) {
        copyOnWrite();
        instance.setVolumeId(value);
        return this;
      }
      /**
       * <code>int32 VolumeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeId() {
        copyOnWrite();
        instance.clearVolumeId();
        return this;
      }

      /**
       * <code>string VolumeName = 2;</code>
       * @return The volumeName.
       */
      @java.lang.Override
      public java.lang.String getVolumeName() {
        return instance.getVolumeName();
      }
      /**
       * <code>string VolumeName = 2;</code>
       * @return The bytes for volumeName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVolumeNameBytes() {
        return instance.getVolumeNameBytes();
      }
      /**
       * <code>string VolumeName = 2;</code>
       * @param value The volumeName to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeName(
          java.lang.String value) {
        copyOnWrite();
        instance.setVolumeName(value);
        return this;
      }
      /**
       * <code>string VolumeName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeName() {
        copyOnWrite();
        instance.clearVolumeName();
        return this;
      }
      /**
       * <code>string VolumeName = 2;</code>
       * @param value The bytes for volumeName to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVolumeNameBytes(value);
        return this;
      }

      /**
       * <code>int32 VolumeOrder = 3;</code>
       * @return The volumeOrder.
       */
      @java.lang.Override
      public int getVolumeOrder() {
        return instance.getVolumeOrder();
      }
      /**
       * <code>int32 VolumeOrder = 3;</code>
       * @param value The volumeOrder to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeOrder(int value) {
        copyOnWrite();
        instance.setVolumeOrder(value);
        return this;
      }
      /**
       * <code>int32 VolumeOrder = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeOrder() {
        copyOnWrite();
        instance.clearVolumeOrder();
        return this;
      }

      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> getChaptersList() {
        return java.util.Collections.unmodifiableList(
            instance.getChaptersList());
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      @java.lang.Override
      public int getChaptersCount() {
        return instance.getChaptersCount();
      }/**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      @java.lang.Override
      public com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse getChapters(int index) {
        return instance.getChapters(index);
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder setChapters(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
        copyOnWrite();
        instance.setChapters(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder setChapters(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setChapters(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder addChapters(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
        copyOnWrite();
        instance.addChapters(value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder addChapters(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse value) {
        copyOnWrite();
        instance.addChapters(index, value);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder addChapters(
          com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addChapters(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder addChapters(
          int index, com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.Builder builderForValue) {
        copyOnWrite();
        instance.addChapters(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder addAllChapters(
          java.lang.Iterable<? extends com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> values) {
        copyOnWrite();
        instance.addAllChapters(values);
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder clearChapters() {
        copyOnWrite();
        instance.clearChapters();
        return this;
      }
      /**
       * <code>repeated .com.example.dmzj_api.pojo.NovelChapterItemResponse Chapters = 4;</code>
       */
      public Builder removeChapters(int index) {
        copyOnWrite();
        instance.removeChapters(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelChapterVolumeResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "volumeId_",
              "volumeName_",
              "volumeOrder_",
              "chapters_",
              com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.class,
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0004\u0004\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelChapterVolumeResponse)
    private static final com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse DEFAULT_INSTANCE;
    static {
      NovelChapterVolumeResponse defaultInstance = new NovelChapterVolumeResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelChapterVolumeResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterVolumeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelChapterVolumeResponse> PARSER;

    public static com.google.protobuf.Parser<NovelChapterVolumeResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NovelChapterItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.dmzj_api.pojo.NovelChapterItemResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 ChapterId = 1;</code>
     * @return The chapterId.
     */
    int getChapterId();

    /**
     * <code>string ChapterName = 2;</code>
     * @return The chapterName.
     */
    java.lang.String getChapterName();
    /**
     * <code>string ChapterName = 2;</code>
     * @return The bytes for chapterName.
     */
    com.google.protobuf.ByteString
        getChapterNameBytes();

    /**
     * <code>int32 ChapterOrder = 3;</code>
     * @return The chapterOrder.
     */
    int getChapterOrder();
  }
  /**
   * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterItemResponse}
   */
  public  static final class NovelChapterItemResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NovelChapterItemResponse, NovelChapterItemResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.dmzj_api.pojo.NovelChapterItemResponse)
      NovelChapterItemResponseOrBuilder {
    private NovelChapterItemResponse() {
      chapterName_ = "";
    }
    public static final int CHAPTERID_FIELD_NUMBER = 1;
    private int chapterId_;
    /**
     * <code>int32 ChapterId = 1;</code>
     * @return The chapterId.
     */
    @java.lang.Override
    public int getChapterId() {
      return chapterId_;
    }
    /**
     * <code>int32 ChapterId = 1;</code>
     * @param value The chapterId to set.
     */
    private void setChapterId(int value) {
      
      chapterId_ = value;
    }
    /**
     * <code>int32 ChapterId = 1;</code>
     */
    private void clearChapterId() {
      
      chapterId_ = 0;
    }

    public static final int CHAPTERNAME_FIELD_NUMBER = 2;
    private java.lang.String chapterName_;
    /**
     * <code>string ChapterName = 2;</code>
     * @return The chapterName.
     */
    @java.lang.Override
    public java.lang.String getChapterName() {
      return chapterName_;
    }
    /**
     * <code>string ChapterName = 2;</code>
     * @return The bytes for chapterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChapterNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(chapterName_);
    }
    /**
     * <code>string ChapterName = 2;</code>
     * @param value The chapterName to set.
     */
    private void setChapterName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      chapterName_ = value;
    }
    /**
     * <code>string ChapterName = 2;</code>
     */
    private void clearChapterName() {
      
      chapterName_ = getDefaultInstance().getChapterName();
    }
    /**
     * <code>string ChapterName = 2;</code>
     * @param value The bytes for chapterName to set.
     */
    private void setChapterNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      chapterName_ = value.toStringUtf8();
      
    }

    public static final int CHAPTERORDER_FIELD_NUMBER = 3;
    private int chapterOrder_;
    /**
     * <code>int32 ChapterOrder = 3;</code>
     * @return The chapterOrder.
     */
    @java.lang.Override
    public int getChapterOrder() {
      return chapterOrder_;
    }
    /**
     * <code>int32 ChapterOrder = 3;</code>
     * @param value The chapterOrder to set.
     */
    private void setChapterOrder(int value) {
      
      chapterOrder_ = value;
    }
    /**
     * <code>int32 ChapterOrder = 3;</code>
     */
    private void clearChapterOrder() {
      
      chapterOrder_ = 0;
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.dmzj_api.pojo.NovelChapterItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.dmzj_api.pojo.NovelChapterItemResponse)
        com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponseOrBuilder {
      // Construct using com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 ChapterId = 1;</code>
       * @return The chapterId.
       */
      @java.lang.Override
      public int getChapterId() {
        return instance.getChapterId();
      }
      /**
       * <code>int32 ChapterId = 1;</code>
       * @param value The chapterId to set.
       * @return This builder for chaining.
       */
      public Builder setChapterId(int value) {
        copyOnWrite();
        instance.setChapterId(value);
        return this;
      }
      /**
       * <code>int32 ChapterId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterId() {
        copyOnWrite();
        instance.clearChapterId();
        return this;
      }

      /**
       * <code>string ChapterName = 2;</code>
       * @return The chapterName.
       */
      @java.lang.Override
      public java.lang.String getChapterName() {
        return instance.getChapterName();
      }
      /**
       * <code>string ChapterName = 2;</code>
       * @return The bytes for chapterName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getChapterNameBytes() {
        return instance.getChapterNameBytes();
      }
      /**
       * <code>string ChapterName = 2;</code>
       * @param value The chapterName to set.
       * @return This builder for chaining.
       */
      public Builder setChapterName(
          java.lang.String value) {
        copyOnWrite();
        instance.setChapterName(value);
        return this;
      }
      /**
       * <code>string ChapterName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterName() {
        copyOnWrite();
        instance.clearChapterName();
        return this;
      }
      /**
       * <code>string ChapterName = 2;</code>
       * @param value The bytes for chapterName to set.
       * @return This builder for chaining.
       */
      public Builder setChapterNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChapterNameBytes(value);
        return this;
      }

      /**
       * <code>int32 ChapterOrder = 3;</code>
       * @return The chapterOrder.
       */
      @java.lang.Override
      public int getChapterOrder() {
        return instance.getChapterOrder();
      }
      /**
       * <code>int32 ChapterOrder = 3;</code>
       * @param value The chapterOrder to set.
       * @return This builder for chaining.
       */
      public Builder setChapterOrder(int value) {
        copyOnWrite();
        instance.setChapterOrder(value);
        return this;
      }
      /**
       * <code>int32 ChapterOrder = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapterOrder() {
        copyOnWrite();
        instance.clearChapterOrder();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.dmzj_api.pojo.NovelChapterItemResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "chapterId_",
              "chapterName_",
              "chapterOrder_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.dmzj_api.pojo.NovelChapterItemResponse)
    private static final com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse DEFAULT_INSTANCE;
    static {
      NovelChapterItemResponse defaultInstance = new NovelChapterItemResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NovelChapterItemResponse.class, defaultInstance);
    }

    public static com.example.dmzj_api.pojo.NovelChapterRes.NovelChapterItemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NovelChapterItemResponse> PARSER;

    public static com.google.protobuf.Parser<NovelChapterItemResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
